/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OpenpawlRouteImport } from './routes/openpawl'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OpenpawlSupportRouteImport } from './routes/openpawl.support'
import { Route as OpenpawlInstallRouteImport } from './routes/openpawl.install'
import { Route as OpenpawlDocsRouteImport } from './routes/openpawl.docs'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter.confirm'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as CloudWaitlistRouteImport } from './routes/cloud.waitlist'
import { Route as CloudStatusRouteImport } from './routes/cloud.status'
import { Route as CloudEvidenceRouteImport } from './routes/cloud.evidence'
import { Route as ApiGithubMarketplaceRouteImport } from './routes/api.github.marketplace'
import { Route as ApiCloudWaitlistRouteImport } from './routes/api.cloud.waitlist'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenpawlRoute = OpenpawlRouteImport.update({
  id: '/openpawl',
  path: '/openpawl',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const OpenpawlSupportRoute = OpenpawlSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => OpenpawlRoute,
} as any)
const OpenpawlInstallRoute = OpenpawlInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => OpenpawlRoute,
} as any)
const OpenpawlDocsRoute = OpenpawlDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => OpenpawlRoute,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const CloudWaitlistRoute = CloudWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => CloudRoute,
} as any)
const CloudStatusRoute = CloudStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => CloudRoute,
} as any)
const CloudEvidenceRoute = CloudEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => CloudRoute,
} as any)
const ApiGithubMarketplaceRoute = ApiGithubMarketplaceRouteImport.update({
  id: '/api/github/marketplace',
  path: '/api/github/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudWaitlistRoute = ApiCloudWaitlistRouteImport.update({
  id: '/api/cloud/waitlist',
  path: '/api/cloud/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/cloud': typeof CloudRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/openpawl': typeof OpenpawlRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/research': typeof ResearchRoute
  '/security': typeof SecurityRoute
  '/site': typeof SiteRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/cloud/evidence': typeof CloudEvidenceRoute
  '/cloud/status': typeof CloudStatusRoute
  '/cloud/waitlist': typeof CloudWaitlistRoute
  '/docs/$': typeof DocsSplatRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/openpawl/docs': typeof OpenpawlDocsRoute
  '/openpawl/install': typeof OpenpawlInstallRoute
  '/openpawl/support': typeof OpenpawlSupportRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/cloud/waitlist': typeof ApiCloudWaitlistRoute
  '/api/github/marketplace': typeof ApiGithubMarketplaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/cloud': typeof CloudRouteWithChildren
  '/contact': typeof ContactRoute
  '/openpawl': typeof OpenpawlRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/security': typeof SecurityRoute
  '/site': typeof SiteRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/cloud/evidence': typeof CloudEvidenceRoute
  '/cloud/status': typeof CloudStatusRoute
  '/cloud/waitlist': typeof CloudWaitlistRoute
  '/docs/$': typeof DocsSplatRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/openpawl/docs': typeof OpenpawlDocsRoute
  '/openpawl/install': typeof OpenpawlInstallRoute
  '/openpawl/support': typeof OpenpawlSupportRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/docs': typeof DocsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/cloud/waitlist': typeof ApiCloudWaitlistRoute
  '/api/github/marketplace': typeof ApiGithubMarketplaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/cloud': typeof CloudRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/openpawl': typeof OpenpawlRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/research': typeof ResearchRoute
  '/security': typeof SecurityRoute
  '/site': typeof SiteRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/cloud/evidence': typeof CloudEvidenceRoute
  '/cloud/status': typeof CloudStatusRoute
  '/cloud/waitlist': typeof CloudWaitlistRoute
  '/docs/$': typeof DocsSplatRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/openpawl/docs': typeof OpenpawlDocsRoute
  '/openpawl/install': typeof OpenpawlInstallRoute
  '/openpawl/support': typeof OpenpawlSupportRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/cloud/waitlist': typeof ApiCloudWaitlistRoute
  '/api/github/marketplace': typeof ApiGithubMarketplaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/careers'
    | '/cloud'
    | '/contact'
    | '/docs'
    | '/openpawl'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/research'
    | '/security'
    | '/site'
    | '/status'
    | '/terms'
    | '/cloud/evidence'
    | '/cloud/status'
    | '/cloud/waitlist'
    | '/docs/$'
    | '/newsletter/confirm'
    | '/openpawl/docs'
    | '/openpawl/install'
    | '/openpawl/support'
    | '/products/$slug'
    | '/docs/'
    | '/products/'
    | '/api/cloud/waitlist'
    | '/api/github/marketplace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/careers'
    | '/cloud'
    | '/contact'
    | '/openpawl'
    | '/pricing'
    | '/privacy'
    | '/research'
    | '/security'
    | '/site'
    | '/status'
    | '/terms'
    | '/cloud/evidence'
    | '/cloud/status'
    | '/cloud/waitlist'
    | '/docs/$'
    | '/newsletter/confirm'
    | '/openpawl/docs'
    | '/openpawl/install'
    | '/openpawl/support'
    | '/products/$slug'
    | '/docs'
    | '/products'
    | '/api/cloud/waitlist'
    | '/api/github/marketplace'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/careers'
    | '/cloud'
    | '/contact'
    | '/docs'
    | '/openpawl'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/research'
    | '/security'
    | '/site'
    | '/status'
    | '/terms'
    | '/cloud/evidence'
    | '/cloud/status'
    | '/cloud/waitlist'
    | '/docs/$'
    | '/newsletter/confirm'
    | '/openpawl/docs'
    | '/openpawl/install'
    | '/openpawl/support'
    | '/products/$slug'
    | '/docs/'
    | '/products/'
    | '/api/cloud/waitlist'
    | '/api/github/marketplace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CloudRoute: typeof CloudRouteWithChildren
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  OpenpawlRoute: typeof OpenpawlRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResearchRoute: typeof ResearchRoute
  SecurityRoute: typeof SecurityRoute
  SiteRoute: typeof SiteRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
  ApiCloudWaitlistRoute: typeof ApiCloudWaitlistRoute
  ApiGithubMarketplaceRoute: typeof ApiGithubMarketplaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openpawl': {
      id: '/openpawl'
      path: '/openpawl'
      fullPath: '/openpawl'
      preLoaderRoute: typeof OpenpawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/openpawl/support': {
      id: '/openpawl/support'
      path: '/support'
      fullPath: '/openpawl/support'
      preLoaderRoute: typeof OpenpawlSupportRouteImport
      parentRoute: typeof OpenpawlRoute
    }
    '/openpawl/install': {
      id: '/openpawl/install'
      path: '/install'
      fullPath: '/openpawl/install'
      preLoaderRoute: typeof OpenpawlInstallRouteImport
      parentRoute: typeof OpenpawlRoute
    }
    '/openpawl/docs': {
      id: '/openpawl/docs'
      path: '/docs'
      fullPath: '/openpawl/docs'
      preLoaderRoute: typeof OpenpawlDocsRouteImport
      parentRoute: typeof OpenpawlRoute
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/cloud/waitlist': {
      id: '/cloud/waitlist'
      path: '/waitlist'
      fullPath: '/cloud/waitlist'
      preLoaderRoute: typeof CloudWaitlistRouteImport
      parentRoute: typeof CloudRoute
    }
    '/cloud/status': {
      id: '/cloud/status'
      path: '/status'
      fullPath: '/cloud/status'
      preLoaderRoute: typeof CloudStatusRouteImport
      parentRoute: typeof CloudRoute
    }
    '/cloud/evidence': {
      id: '/cloud/evidence'
      path: '/evidence'
      fullPath: '/cloud/evidence'
      preLoaderRoute: typeof CloudEvidenceRouteImport
      parentRoute: typeof CloudRoute
    }
    '/api/github/marketplace': {
      id: '/api/github/marketplace'
      path: '/api/github/marketplace'
      fullPath: '/api/github/marketplace'
      preLoaderRoute: typeof ApiGithubMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloud/waitlist': {
      id: '/api/cloud/waitlist'
      path: '/api/cloud/waitlist'
      fullPath: '/api/cloud/waitlist'
      preLoaderRoute: typeof ApiCloudWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CloudRouteChildren {
  CloudEvidenceRoute: typeof CloudEvidenceRoute
  CloudStatusRoute: typeof CloudStatusRoute
  CloudWaitlistRoute: typeof CloudWaitlistRoute
}

const CloudRouteChildren: CloudRouteChildren = {
  CloudEvidenceRoute: CloudEvidenceRoute,
  CloudStatusRoute: CloudStatusRoute,
  CloudWaitlistRoute: CloudWaitlistRoute,
}

const CloudRouteWithChildren = CloudRoute._addFileChildren(CloudRouteChildren)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface OpenpawlRouteChildren {
  OpenpawlDocsRoute: typeof OpenpawlDocsRoute
  OpenpawlInstallRoute: typeof OpenpawlInstallRoute
  OpenpawlSupportRoute: typeof OpenpawlSupportRoute
}

const OpenpawlRouteChildren: OpenpawlRouteChildren = {
  OpenpawlDocsRoute: OpenpawlDocsRoute,
  OpenpawlInstallRoute: OpenpawlInstallRoute,
  OpenpawlSupportRoute: OpenpawlSupportRoute,
}

const OpenpawlRouteWithChildren = OpenpawlRoute._addFileChildren(
  OpenpawlRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CloudRoute: CloudRouteWithChildren,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  OpenpawlRoute: OpenpawlRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResearchRoute: ResearchRoute,
  SecurityRoute: SecurityRoute,
  SiteRoute: SiteRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  NewsletterConfirmRoute: NewsletterConfirmRoute,
  ApiCloudWaitlistRoute: ApiCloudWaitlistRoute,
  ApiGithubMarketplaceRoute: ApiGithubMarketplaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
