export const OPENPAWL_TRIGGER_LABEL = "openpawl";
export const OPENPAWL_APPROVED_LABEL = "openpawl-approved";
export const OPENPAWL_REVIEW_TASK = "Review and analyse the changes in this repository context";
export const OPENPAWL_PLAN_TASK = "Plan the next implementation steps for the repository changes";
export const OPENPAWL_ADD_TESTS_TASK = "Add targeted tests for the repository changes";
export const OPENPAWL_FIX_FAILING_TESTS_TASK = "Fix the failing tests for the repository changes";

type ParsedCommandName = "review" | "plan" | "add tests" | "fix failing tests" | "apply";
type ParsedCommandPrefix = "/" | "@";

export interface ParsedOpenPawlCommand {
  command: ParsedCommandName;
  prefix: ParsedCommandPrefix;
  task: string;
  sourceLine: string;
}

export interface OpenPawlTriggerResolution {
  shouldRun: boolean;
  reason: string;
  task: string;
  repoPath: string;
  mode: "dry-run" | "write";
  issueNumber?: number;
  issueIsPullRequest: boolean;
  baseRepoFullName?: string;
  headRepoFullName?: string;
  baseRef?: string;
  approvedWrite: boolean;
  approvalSource: "none" | "apply_command" | "approved_label" | "workflow_dispatch";
  sourceTitle?: string;
  source: "workflow_dispatch" | "pull_request" | "issue_comment" | "issues" | "none";
}

interface GithubEventLike {
  action?: string;
  comment?: {
    body?: string;
    title?: string;
    author_association?: string;
    user?: {
      login?: string;
      type?: string;
    };
  };
  issue?: {
    number?: number;
    title?: string;
    body?: string;
    pull_request?: unknown;
  };
  pull_request?: {
    number?: number;
    title?: string;
    body?: string;
    labels?: Array<{ name?: string }>;
    base?: {
      ref?: string;
    };
    head?: {
      repo?: {
        full_name?: string;
      };
    };
  };
  label?: {
    name?: string;
  };
  repository?: {
    full_name?: string;
    default_branch?: string;
  };
  inputs?: {
    task?: string;
    repo_path?: string;
    mode?: string;
  };
}

const COMMAND_TASKS = new Map<string, string>([
  ["review", OPENPAWL_REVIEW_TASK],
  ["plan", OPENPAWL_PLAN_TASK],
  ["add tests", OPENPAWL_ADD_TESTS_TASK],
  ["fix failing tests", OPENPAWL_FIX_FAILING_TESTS_TASK],
]);

const MAINTAINER_ASSOCIATIONS = new Set(["OWNER", "MEMBER", "COLLABORATOR"]);

function trimToSingleSpace(value: string): string {
  return value.trim().replace(/\s+/g, " ").toLowerCase();
}

function isOpenPawlReportComment(commentBody: string): boolean {
  const normalized = commentBody.trim().toLowerCase();
  return normalized.includes("openpawl agent run report")
    || normalized.includes("openpawl run report")
    || normalized.includes("generated by [openpawl]");
}

function isLabelMatch(labelName: unknown): boolean {
  return typeof labelName === "string" && labelName.toLowerCase() === OPENPAWL_TRIGGER_LABEL;
}

function isApprovalLabelMatch(labelName: unknown): boolean {
  return typeof labelName === "string" && labelName.toLowerCase() === OPENPAWL_APPROVED_LABEL;
}

function pickLabelName(payload: GithubEventLike): string | undefined {
  if (typeof payload.label?.name === "string") {
    return payload.label.name;
  }
  return undefined;
}

function getRepositoryFullName(payload: GithubEventLike, fallback?: string): string | undefined {
  if (typeof payload.repository?.full_name === "string") {
    return payload.repository.full_name;
  }
  if (fallback) {
    return fallback;
  }
  return undefined;
}

function getIssueNumber(payload: GithubEventLike): number | undefined {
  const issueNumber = payload.issue?.number;
  if (typeof issueNumber === "number" && Number.isFinite(issueNumber)) {
    return issueNumber;
  }
  return undefined;
}

function isPullRequestIssue(payload: GithubEventLike): boolean {
  return typeof payload.issue?.pull_request !== "undefined";
}

function isBotAuthoredComment(payload: GithubEventLike): boolean {
  const userType = payload.comment?.user?.type;
  if (typeof userType === "string" && userType.toLowerCase() === "bot") {
    return true;
  }

  const login = payload.comment?.user?.login;
  return typeof login === "string" && login.toLowerCase().endsWith("[bot]");
}

function getHeadRepo(payload: GithubEventLike): string | undefined {
  const fullName = payload.pull_request?.head?.repo?.full_name;
  return typeof fullName === "string" ? fullName : undefined;
}

function getBaseRef(payload: GithubEventLike): string {
  const prBase = payload.pull_request?.base?.ref;
  if (typeof prBase === "string" && prBase.trim()) {
    return prBase;
  }
  const defaultBranch = payload.repository?.default_branch;
  return typeof defaultBranch === "string" && defaultBranch.trim() ? defaultBranch : "main";
}

function isMaintainerAssociation(value: unknown): boolean {
  return typeof value === "string" && MAINTAINER_ASSOCIATIONS.has(value.toUpperCase());
}

function getSourceTitle(payload: GithubEventLike): string {
  const title = payload.pull_request?.title ?? payload.issue?.title;
  return typeof title === "string" && title.trim() ? title.trim() : "repository changes";
}

function getSourceBody(payload: GithubEventLike): string {
  const body = payload.pull_request?.body ?? payload.issue?.body;
  return typeof body === "string" && body.trim() ? body.trim() : "No issue or pull request body was provided.";
}

function buildApprovedApplyTask(payload: GithubEventLike, issueNumber: number, issueIsPullRequest: boolean): string {
  const sourceKind = issueIsPullRequest ? "pull request" : "issue";
  const title = getSourceTitle(payload);
  const body = getSourceBody(payload);
  return [
    `Approved Openpawl apply for ${sourceKind} #${issueNumber}: ${title}`,
    "",
    body,
  ].join("\n");
}

export function parseOpenPawlCommand(commentBody: string): ParsedOpenPawlCommand | null {
  if (!commentBody) return null;

  const lines = commentBody.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = trimToSingleSpace(line);
    const match = /^([/@])openpawl(?:\s+(.*))?$/i.exec(trimmed);
    if (!match) continue;

    const prefix = match[1] as ParsedCommandPrefix;
    const commandText = match[2]?.trim() ?? "";
    const normalizedCommand = commandText.toLowerCase();
    const task = COMMAND_TASKS.get(normalizedCommand);
    if (prefix === "/" && normalizedCommand === "apply") {
      return {
        command: normalizedCommand as ParsedCommandName,
        prefix,
        task: "",
        sourceLine: line,
      };
    }
    if (!task) {
      continue;
    }

    return {
      command: normalizedCommand as ParsedCommandName,
      prefix,
      task,
      sourceLine: line,
    };
  }

  return null;
}

export function resolveOpenPawlTriggerFromEvent(
  event: GithubEventLike | null | undefined,
  options: {
    eventName: string;
    workflowTask?: string;
    workflowRepoPath?: string;
    workflowMode?: "dry-run" | "write" | string;
    workflowRepository?: string;
  }
): OpenPawlTriggerResolution {
  const eventName = eventNameToMode(options.eventName);
  const payload = event ?? {};
  const baseRepo = getRepositoryFullName(payload, options.workflowRepository);
  const eventInputs = payload.inputs;
  const resolvedWorkflowTask = options.workflowTask ?? eventInputs?.task;
  const resolvedWorkflowRepoPath = options.workflowRepoPath ?? eventInputs?.repo_path;
  const resolvedWorkflowMode = options.workflowMode ?? eventInputs?.mode;

  switch (eventName) {
    case "workflow_dispatch": {
      const rawMode = typeof resolvedWorkflowMode === "string" ? resolvedWorkflowMode.toLowerCase() : "";
      const mode = rawMode === "write" ? "write" : "dry-run";
      return {
        shouldRun: true,
        reason: "Manual workflow_dispatch trigger.",
        task: resolvedWorkflowTask || "review changes and suggest improvements",
        repoPath: resolvedWorkflowRepoPath || ".",
        mode,
        issueIsPullRequest: false,
        baseRepoFullName: baseRepo,
        baseRef: getBaseRef(payload),
        approvedWrite: false,
        approvalSource: "workflow_dispatch",
        source: "workflow_dispatch",
      };
    }
    case "pull_request": {
      const issueNumber = payload.pull_request?.number;
      const prNumber = typeof issueNumber === "number" && Number.isFinite(issueNumber) ? issueNumber : undefined;
      const isLabeledTrigger = payload.action === "labeled" && isLabelMatch(pickLabelName(payload));
      const isApprovedLabelTrigger = payload.action === "labeled" && isApprovalLabelMatch(pickLabelName(payload));
      if (!isLabeledTrigger && payload.action !== undefined && payload.action !== "opened" && payload.action !== "synchronize" && payload.action !== "reopened") {
        if (isApprovedLabelTrigger && prNumber !== undefined) {
          return {
            shouldRun: true,
            reason: "Pull request labeled with openpawl-approved.",
            task: buildApprovedApplyTask(payload, prNumber, true),
            repoPath: ".",
            mode: "write",
            issueNumber: prNumber,
            issueIsPullRequest: true,
            baseRepoFullName: baseRepo,
            headRepoFullName: getHeadRepo(payload),
            baseRef: getBaseRef(payload),
            approvedWrite: true,
            approvalSource: "approved_label",
            sourceTitle: getSourceTitle(payload),
            source: "pull_request",
          };
        }
        return {
          shouldRun: false,
          reason: "Unsupported pull_request action for automatic Openpawl runs.",
          task: OPENPAWL_REVIEW_TASK,
          repoPath: ".",
          mode: "dry-run",
          issueIsPullRequest: true,
          baseRepoFullName: baseRepo,
          headRepoFullName: getHeadRepo(payload),
          baseRef: getBaseRef(payload),
          approvedWrite: false,
          approvalSource: "none",
          source: "pull_request",
        };
      }
      if (prNumber === undefined) {
        return {
          shouldRun: false,
          reason: "pull_request event missing pull request number.",
          task: OPENPAWL_REVIEW_TASK,
          repoPath: ".",
          mode: "dry-run",
          issueIsPullRequest: true,
          baseRepoFullName: baseRepo,
          headRepoFullName: getHeadRepo(payload),
          baseRef: getBaseRef(payload),
          approvedWrite: false,
          approvalSource: "none",
          source: "pull_request",
        };
      }
      if (isApprovedLabelTrigger) {
        return {
          shouldRun: true,
          reason: "Pull request labeled with openpawl-approved.",
          task: buildApprovedApplyTask(payload, prNumber, true),
          repoPath: ".",
          mode: "write",
          issueNumber: prNumber,
          issueIsPullRequest: true,
          baseRepoFullName: baseRepo,
          headRepoFullName: getHeadRepo(payload),
          baseRef: getBaseRef(payload),
          approvedWrite: true,
          approvalSource: "approved_label",
          sourceTitle: getSourceTitle(payload),
          source: "pull_request",
        };
      }
      return {
        shouldRun: true,
        reason: isLabeledTrigger ? "Pull request labeled with openpawl." : "Pull request event.",
        task: OPENPAWL_REVIEW_TASK,
        repoPath: ".",
        mode: "dry-run",
        issueNumber: prNumber,
        issueIsPullRequest: true,
        baseRepoFullName: baseRepo,
        headRepoFullName: getHeadRepo(payload),
        baseRef: getBaseRef(payload),
        approvedWrite: false,
        approvalSource: "none",
        source: "pull_request",
      };
    }
    case "issue_comment": {
      const body = typeof payload.comment?.body === "string" ? payload.comment.body : "";
      if (isOpenPawlReportComment(body)) {
        return {
          shouldRun: false,
          reason: "Ignoring Openpawl report comment to prevent recursive Openpawl runs.",
          task: OPENPAWL_REVIEW_TASK,
          repoPath: ".",
          mode: "dry-run",
          issueIsPullRequest: isPullRequestIssue(payload),
          issueNumber: getIssueNumber(payload),
          baseRepoFullName: baseRepo,
          baseRef: getBaseRef(payload),
          approvedWrite: false,
          approvalSource: "none",
          source: "issue_comment",
        };
      }

      if (isBotAuthoredComment(payload)) {
        return {
          shouldRun: false,
          reason: "Ignoring bot-authored issue_comment to prevent recursive Openpawl runs.",
          task: OPENPAWL_REVIEW_TASK,
          repoPath: ".",
          mode: "dry-run",
          issueIsPullRequest: isPullRequestIssue(payload),
          issueNumber: getIssueNumber(payload),
          baseRepoFullName: baseRepo,
          baseRef: getBaseRef(payload),
          approvedWrite: false,
          approvalSource: "none",
          source: "issue_comment",
        };
      }

      const command = parseOpenPawlCommand(body);
      if (!command) {
        return {
          shouldRun: false,
          reason: "No supported /openpawl or @openpawl command found in issue_comment body.",
          task: OPENPAWL_REVIEW_TASK,
          repoPath: ".",
          mode: "dry-run",
          issueIsPullRequest: isPullRequestIssue(payload),
          issueNumber: getIssueNumber(payload),
          baseRepoFullName: baseRepo,
          baseRef: getBaseRef(payload),
          approvedWrite: false,
          approvalSource: "none",
          source: "issue_comment",
        };
      }
      const issueNumber = getIssueNumber(payload);
      if (issueNumber === undefined) {
        return {
          shouldRun: false,
          reason: "issue_comment event missing issue number.",
          task: command.task || OPENPAWL_REVIEW_TASK,
          repoPath: ".",
          mode: "dry-run",
          issueIsPullRequest: isPullRequestIssue(payload),
          issueNumber,
          baseRepoFullName: baseRepo,
          baseRef: getBaseRef(payload),
          approvedWrite: false,
          approvalSource: "none",
          source: "issue_comment",
        };
      }
      if (command.command === "apply") {
        const issueIsPullRequest = isPullRequestIssue(payload);
        if (!isMaintainerAssociation(payload.comment?.author_association)) {
          return {
            shouldRun: false,
            reason: "/openpawl apply requires a maintainer comment author association.",
            task: buildApprovedApplyTask(payload, issueNumber, issueIsPullRequest),
            repoPath: ".",
            mode: "dry-run",
            issueNumber,
            issueIsPullRequest,
            baseRepoFullName: baseRepo,
            baseRef: getBaseRef(payload),
            approvedWrite: false,
            approvalSource: "none",
            sourceTitle: getSourceTitle(payload),
            source: "issue_comment",
          };
        }
        return {
          shouldRun: true,
          reason: "Maintainer /openpawl apply command detected.",
          task: buildApprovedApplyTask(payload, issueNumber, issueIsPullRequest),
          repoPath: ".",
          mode: "write",
          issueNumber,
          issueIsPullRequest,
          baseRepoFullName: baseRepo,
          baseRef: getBaseRef(payload),
          approvedWrite: true,
          approvalSource: "apply_command",
          sourceTitle: getSourceTitle(payload),
          source: "issue_comment",
        };
      }
      return {
        shouldRun: true,
        reason: "Supported Openpawl comment command detected.",
        task: command.task,
        repoPath: ".",
        mode: "dry-run",
        issueNumber,
        issueIsPullRequest: isPullRequestIssue(payload),
        baseRepoFullName: baseRepo,
        baseRef: getBaseRef(payload),
        approvedWrite: false,
        approvalSource: "none",
        source: "issue_comment",
      };
    }
    case "issues": {
      const action = payload.action;
      const labelName = pickLabelName(payload);
      const isApprovedLabelTrigger = action === "labeled" && isApprovalLabelMatch(labelName);
      if (action !== "labeled" || (!isLabelMatch(labelName) && !isApprovedLabelTrigger)) {
        return {
          shouldRun: false,
          reason: "issues event is not an openpawl label application.",
          task: OPENPAWL_REVIEW_TASK,
          repoPath: ".",
          mode: "dry-run",
          issueIsPullRequest: false,
          issueNumber: getIssueNumber(payload),
          baseRepoFullName: baseRepo,
          baseRef: getBaseRef(payload),
          approvedWrite: false,
          approvalSource: "none",
          source: "issues",
        };
      }
      const issueNumber = getIssueNumber(payload);
      if (issueNumber === undefined) {
        return {
          shouldRun: false,
          reason: "issues labeled event missing issue number.",
          task: OPENPAWL_REVIEW_TASK,
          repoPath: ".",
          mode: "dry-run",
          issueIsPullRequest: false,
          baseRepoFullName: baseRepo,
          baseRef: getBaseRef(payload),
          approvedWrite: false,
          approvalSource: "none",
          source: "issues",
        };
      }
      if (isApprovedLabelTrigger) {
        return {
          shouldRun: true,
          reason: "Issue labeled with openpawl-approved.",
          task: buildApprovedApplyTask(payload, issueNumber, false),
          repoPath: ".",
          mode: "write",
          issueNumber,
          issueIsPullRequest: false,
          baseRepoFullName: baseRepo,
          baseRef: getBaseRef(payload),
          approvedWrite: true,
          approvalSource: "approved_label",
          sourceTitle: getSourceTitle(payload),
          source: "issues",
        };
      }
      return {
        shouldRun: true,
        reason: "Issue labeled with openpawl.",
        task: OPENPAWL_REVIEW_TASK,
        repoPath: ".",
        mode: "dry-run",
        issueNumber,
        issueIsPullRequest: false,
        baseRepoFullName: baseRepo,
        baseRef: getBaseRef(payload),
        approvedWrite: false,
        approvalSource: "none",
        source: "issues",
      };
    }
    default:
      return {
        shouldRun: false,
        reason: `Unsupported event: ${options.eventName}.`,
        task: OPENPAWL_REVIEW_TASK,
        repoPath: ".",
        mode: "dry-run",
        issueIsPullRequest: false,
        baseRepoFullName: baseRepo,
        baseRef: getBaseRef(payload),
        approvedWrite: false,
        approvalSource: "none",
        source: "none",
      };
  }
}

function eventNameToMode(eventName: string): "workflow_dispatch" | "pull_request" | "issue_comment" | "issues" | "none" {
  if (eventName === "workflow_dispatch") return "workflow_dispatch";
  if (eventName === "pull_request") return "pull_request";
  if (eventName === "issue_comment") return "issue_comment";
  if (eventName === "issues") return "issues";
  return "none";
}
