"""Benchmark package for frontend design evaluation."""

from pawlbench_design.embeddings import EmbeddingConfig, EmbeddingResult, build_encoder_baselines
from pawlbench_design.datasets import (
    ReportConfig,
    ReportResult,
    SplitConfig,
    SplitResult,
    ValidationConfig,
    ValidationResult,
    export_dataset_report,
    split_dataset,
    validate_dataset,
)
from pawlbench_design.evaluator import EvalConfig, EvalResult, evaluate_jitter_pairs
from pawlbench_design.label_app import (
    LabelAppConfig,
    LabelAppResult,
    LabelAppStore,
    run_label_app,
)
from pawlbench_design.labels import (
    LabelAuditConfig,
    LabelAuditResult,
    LabelQueueConfig,
    LabelQueueResult,
    LabelReportConfig,
    LabelReportResult,
    LabelSetReviewerConfig,
    LabelSetReviewerResult,
    LabelSuggestConfig,
    LabelSuggestResult,
    LabelValidationConfig,
    LabelValidationResult,
    audit_labels,
    build_label_queue,
    export_label_report,
    set_label_reviewer,
    suggest_labels,
    validate_labels,
)
from pawlbench_design.vision_embeddings import (
    VisionEmbeddingConfig,
    VisionEmbeddingResult,
    build_vision_baselines,
)

__version__ = "0.1.0"

__all__ = [
    "EmbeddingConfig",
    "EmbeddingResult",
    "EvalConfig",
    "EvalResult",
    "LabelAppConfig",
    "LabelAppResult",
    "LabelAppStore",
    "LabelAuditConfig",
    "LabelAuditResult",
    "LabelQueueConfig",
    "LabelQueueResult",
    "LabelReportConfig",
    "LabelReportResult",
    "LabelSetReviewerConfig",
    "LabelSetReviewerResult",
    "LabelSuggestConfig",
    "LabelSuggestResult",
    "LabelValidationConfig",
    "LabelValidationResult",
    "ReportConfig",
    "ReportResult",
    "SplitConfig",
    "SplitResult",
    "ValidationConfig",
    "ValidationResult",
    "VisionEmbeddingConfig",
    "VisionEmbeddingResult",
    "__version__",
    "audit_labels",
    "build_encoder_baselines",
    "build_label_queue",
    "build_vision_baselines",
    "export_dataset_report",
    "export_label_report",
    "split_dataset",
    "validate_dataset",
    "validate_labels",
    "evaluate_jitter_pairs",
    "run_label_app",
    "set_label_reviewer",
    "suggest_labels",
]
