"""Benchmark package for frontend design evaluation."""

from pawlbench_design.embeddings import EmbeddingConfig, EmbeddingResult, build_encoder_baselines
from pawlbench_design.datasets import (
    ReportConfig,
    ReportResult,
    SplitConfig,
    SplitResult,
    ValidationConfig,
    ValidationResult,
    export_dataset_report,
    split_dataset,
    validate_dataset,
)
from pawlbench_design.evaluator import EvalConfig, EvalResult, evaluate_jitter_pairs
from pawlbench_design.hard_pairs import HardPairConfig, HardPairResult, build_hard_pairs
from pawlbench_design.label_app import (
    LabelAppConfig,
    LabelAppResult,
    LabelAppStore,
    run_label_app,
)
from pawlbench_design.labels import (
    LabelAuditConfig,
    LabelAuditResult,
    LabelDiffConfig,
    LabelDiffResult,
    LabelQueueConfig,
    LabelQueueResult,
    LabelReportConfig,
    LabelReportResult,
    LabelResuggestConfig,
    LabelResuggestResult,
    LabelSetReviewerConfig,
    LabelSetReviewerResult,
    LabelSuggestConfig,
    LabelSuggestResult,
    LabelValidationConfig,
    LabelValidationResult,
    audit_labels,
    build_label_queue,
    diff_labels,
    export_label_report,
    resuggest_labels,
    set_label_reviewer,
    suggest_labels,
    validate_labels,
)
from pawlbench_design.taste import (
    TasteProfile,
    explain_taste_decision,
    load_taste_profile,
    score_pair_with_taste,
    suggest_label_with_taste,
)
from pawlbench_design.vision_embeddings import (
    VisionEmbeddingConfig,
    VisionEmbeddingResult,
    build_vision_baselines,
)

__version__ = "0.1.0"

__all__ = [
    "EmbeddingConfig",
    "EmbeddingResult",
    "EvalConfig",
    "EvalResult",
    "HardPairConfig",
    "HardPairResult",
    "LabelAppConfig",
    "LabelAppResult",
    "LabelAppStore",
    "LabelAuditConfig",
    "LabelAuditResult",
    "LabelDiffConfig",
    "LabelDiffResult",
    "LabelQueueConfig",
    "LabelQueueResult",
    "LabelReportConfig",
    "LabelReportResult",
    "LabelResuggestConfig",
    "LabelResuggestResult",
    "LabelSetReviewerConfig",
    "LabelSetReviewerResult",
    "LabelSuggestConfig",
    "LabelSuggestResult",
    "LabelValidationConfig",
    "LabelValidationResult",
    "ReportConfig",
    "ReportResult",
    "SplitConfig",
    "SplitResult",
    "TasteProfile",
    "ValidationConfig",
    "ValidationResult",
    "VisionEmbeddingConfig",
    "VisionEmbeddingResult",
    "__version__",
    "audit_labels",
    "build_encoder_baselines",
    "build_hard_pairs",
    "build_label_queue",
    "build_vision_baselines",
    "diff_labels",
    "evaluate_jitter_pairs",
    "explain_taste_decision",
    "export_dataset_report",
    "export_label_report",
    "load_taste_profile",
    "resuggest_labels",
    "run_label_app",
    "score_pair_with_taste",
    "set_label_reviewer",
    "split_dataset",
    "suggest_label_with_taste",
    "suggest_labels",
    "validate_dataset",
    "validate_labels",
]
