import * as fs from "fs/promises";
import * as path from "path";
import { exec } from "child_process";
import { promisify } from "util";
import {
  AgentState,
  AgentMessage,
  AgentNode,
  ReadinessGateResult,
  ReadinessGateStatus,
  RepoScanResult,
  ContextPack,
  ScopeAnalysisResult,
  FileSelectionResult,
  PatchPlan,
  ValidationResult,
  ReportResult,
} from "../state/schema";
import { createContextPack, compactContextForPrompt } from "./context";
import {
  LlmCompletionResult,
  LlmProvider,
  ProviderResponseShapeError,
} from "../providers/llm";
import {
  ProviderJsonOutputError,
  parsePatchPlanResponse,
  parseScopeAnalysisResponse,
} from "../providers/json-output";
import { TraceLedger } from "../ledger/trace";
import {
  SafetyViolationError,
  assertWriteSafe,
  isSecretFile,
  SCAN_IGNORED_DIRS,
  SCAN_MAX_FILES,
  SCAN_MAX_BYTES,
} from "../safety";

const execAsync = promisify(exec);

export const activeLedgers = new Map<string, TraceLedger>();

const BINARY_FILE_EXTENSION_RE =
  /\.(png|jpg|jpeg|gif|ico|woff|woff2|ttf|eot|otf|mp4|webm|mp3|pdf|zip|tar|gz|rar|bin|exe|dll|so|dylib)$/i;

const PLACEHOLDER_VALIDATION_COMMAND = "echo placeholder validation skipped";
const WRITE_MODE_MIN_VALIDATION_CONFIDENCE = 0.85;
const DEFAULT_SCOPE_ANALYSIS_MAX_TOKENS = 1200;
const DEFAULT_PATCH_PLAN_MAX_TOKENS = 1600;
const MIN_CONTEXTUAL_QUERY_WORDS = 3;
const SCOPE_CONTEXT_PROMPT_MARKER = "Scope Context Pack";
const PATCH_CONTEXT_PROMPT_MARKER = "Patch Context Pack";
const PROMPT_METADATA_MAX_CHARS = 12_000;
const PATCH_FILE_EXCERPT_CHARS = 240;
const UNCLOSED_PATH_SEGMENTS = new Set([".", "..", ""]);
const TEST_DIR_SEGMENTS = new Set(["test", "tests", "__tests__"]);
const TEST_FILE_NAME_MARKERS = new Set(["test", "tests", "spec"]);
const MAX_UNGROUNDED_ABSOLUTE = 3;
const MAX_UNGROUNDED_RATIO = 0.6;
const VALIDATION_DECISION_UNAVAILABLE_CONFIDENCE = 0.0;
const SCOPE_ANALYSIS_JSON_SCHEMA = {
  type: "object",
  properties: {
    rationale: { type: "string" },
    affectedModules: {
      type: "array",
      items: { type: "string" },
    },
    proposedModifications: {
      type: "array",
      items: { type: "string" },
    },
    proposedCreations: {
      type: "array",
      items: { type: "string" },
    },
  },
  required: ["rationale", "affectedModules", "proposedModifications", "proposedCreations"],
  additionalProperties: false,
};
const PATCH_PLAN_JSON_SCHEMA = {
  type: "object",
  properties: {
    rationale: { type: "string" },
    chunks: {
      type: "array",
      items: {
        type: "object",
        properties: {
          type: { type: "string", enum: ["create", "modify", "delete"] },
          file: { type: "string" },
          description: { type: "string" },
        },
        required: ["type", "file", "description"],
        additionalProperties: false,
      },
      minItems: 0,
      maxItems: 5,
    },
  },
  required: ["rationale", "chunks"],
  additionalProperties: false,
};

const SCOPE_ANALYSIS_JSON_SCHEMA_PROMPT = JSON.stringify(SCOPE_ANALYSIS_JSON_SCHEMA, null, 2);
const PATCH_PLAN_JSON_SCHEMA_PROMPT = JSON.stringify(PATCH_PLAN_JSON_SCHEMA, null, 2);
const GENERATED_BY_OPENPAWL_COMMENT = "Generated by Openpawl.";

const SCOPED_VALIDATION_COMMANDS: ReadonlyArray<{
  readonly id: string;
  readonly pathPrefix: string;
  readonly command: string;
  readonly confidence: number;
}> = [
  {
    id: "packages/core",
    pathPrefix: "packages/core",
    command: "bun --filter @codepawl/core test",
    confidence: 0.98,
  },
  {
    id: "packages/cli",
    pathPrefix: "packages/cli",
    command: "bun --filter @codepawl/cli test",
    confidence: 0.98,
  },
  {
    id: "packages/shared",
    pathPrefix: "packages/shared",
    command: "bun --filter @codepawl/shared typecheck",
    confidence: 0.98,
  },
  {
    id: "apps/web",
    pathPrefix: "apps/web",
    command: "bun --filter @codepawl/web typecheck",
    confidence: 0.98,
  },
];

function resolveStructuredOutputFormatMode(state: AgentState): "json_schema" | "json_object" {
  return state.context.structuredOutputMode === "json_object"
    ? "json_object"
    : "json_schema";
}

function buildStructuredResponseFormatForSchema(
  purpose: "scope_analysis" | "patch_plan",
  responseFormat: "json_schema" | "json_object",
  schema: Record<string, unknown>
): { type: "json_object" } | { type: "json_schema"; name: string; schema: Record<string, unknown>; strict: boolean } {
  if (responseFormat === "json_object") {
    return { type: "json_object" };
  }

  return {
    type: "json_schema",
    name: purpose,
    schema,
    strict: true,
  };
}

function sanitizeForPromptMetrics(messages: ReadonlyArray<{ content: string }>): number {
  return Math.min(
    PROMPT_METADATA_MAX_CHARS,
    messages.reduce((sum, message) => sum + message.content.length, 0)
  );
}

function createPromptMetadata(messages: ReadonlyArray<{ content: string }>): {
  messageCount: number;
  totalChars: number;
  bounded: boolean;
} {
  const unbounded = messages.reduce((sum, message) => sum + message.content.length, 0);
  return {
    messageCount: messages.length,
    totalChars: Math.min(PROMPT_METADATA_MAX_CHARS, unbounded),
    bounded: unbounded > PROMPT_METADATA_MAX_CHARS,
  };
}

function isBinaryFilePath(filePath: string): boolean {
  return BINARY_FILE_EXTENSION_RE.test(filePath);
}

function isReviewOnlyTask(query: string): boolean {
  const normalized = query.toLowerCase();
  const hasReviewIntent = /\b(review|analyse|analyze|inspect|audit)\b/.test(normalized);
  const hasChangeIntent = /\b(add|create|implement|fix|modify|update|delete|remove|refactor|write|generate)\b/.test(normalized);
  return hasReviewIntent && !hasChangeIntent;
}

function tokenizeWords(value: string): string[] {
  return value
    .toLowerCase()
    .split(/[^a-z0-9_-]+/)
    .map((token) => token.trim())
    .filter((token) => token.length > 0);
}

function isSupportedTask(query: string): boolean {
  const normalized = query.toLowerCase();
  if (!normalized.trim()) {
    return false;
  }
  if (/\b(poem|essay|song|music|image|video|presentation|marketing|finance|invest|purchase|buy|cook|travel|vacation|design\s+(a\s+)?logo)\b/.test(normalized)) {
    return false;
  }

  return /\b(add|create|implement|fix|update|remove|refactor|generate|write|test|tests|review|analyse|analyze|inspect|audit|document|scan|validate|lint|run|migrate|rename|improve|cleanup)\b/.test(normalized);
}

function isLikelyClearObjective(query: string): boolean {
  const tokens = tokenizeWords(query);
  if (tokens.length <= 1) {
    return false;
  }
  if (tokens.length >= MIN_CONTEXTUAL_QUERY_WORDS) {
    return true;
  }
  const hasContextHint = /\b(file|files|function|module|component|package|tests?|bug|error|readme|config|docs?|endpoint|api|route|class|type|script)\b/.test(query.toLowerCase());
  const hasRepoPathHint = /(?:\b(?:src|packages|tests?|lib|app)\b|\/[\w.-]+|\.[jt]s[x]?|\.[cm]?[px]?h?pp?)/.test(query.toLowerCase());
  return hasContextHint || hasRepoPathHint;
}

function hasEnoughContext(query: string, contextPack: ContextPack | undefined): boolean {
  if (query.toLowerCase().includes("--") || query.toLowerCase().includes("/bin/")) {
    return false;
  }
  const candidateCount = contextPack?.metrics?.candidateFiles ?? 0;
  if (tokenizeWords(query).length === 1) {
    return false;
  }
  if (candidateCount >= 1) {
    return true;
  }
  return isLikelyClearObjective(query);
}

function isUnsafeWriteIntent(query: string): boolean {
  const normalized = query.toLowerCase();
  const destructiveVerbs = /\b(delete|remove|modify|destroy|erase|wipe|purge|drop|truncate|rewrite|rebase|nuke|expose|reveal)\b/;
  const destructiveQualifiers = /\b(all|entire|whole|every|everything|all of)\b/;
  const sensitiveTargets = /\b(env|\.env|environment file|environment files|environment variable|environment variables|secret|secrets|token|tokens|api key|apikey|api-key|credential|credentials|lock|locks|lockfile|lockfiles|password|passwords|key|keys)\b/;
  const repoTargets = /\b(file|files|repo|repository|project|codebase|directory|directories|dir|dirs)\b/;

  if (!destructiveVerbs.test(normalized)) {
    return false;
  }

  if (sensitiveTargets.test(normalized)) {
    return true;
  }

  if (destructiveQualifiers.test(normalized) && repoTargets.test(normalized)) {
    return true;
  }

  if (repoTargets.test(normalized) && /\b(repo|repository|project|codebase)\b/.test(normalized)) {
    return true;
  }

  return /\b(delete|remove|expose|reveal)\b/.test(normalized) && /(?:\b(file|files)\b.*\b(all|entire|whole|every|everything)\b|\b(all|entire|whole|every|everything)\b.*\b(file|files)\b)/.test(normalized);
}

function evaluateReadiness(state: AgentState): ReadinessGateResult {
  const query = state.query;
  const reasons: string[] = [];
  const blockers: string[] = [];
  const warnings: string[] = [];

  let status: ReadinessGateStatus = "ready";

  if (!state.context.workspaceDir || state.context.workspaceDir.length === 0 || !state.repoScanResult) {
    blockers.push("Repository path does not appear to be valid for scanning.");
    status = "unsafe";
  }

  if (!isSupportedTask(query)) {
    blockers.push("Task intent appears unsupported for the Openpawl code workflow.");
    status = "unsupported";
  }

  if (!isLikelyClearObjective(query)) {
    reasons.push("Task objective is too vague; include what file, module, behavior, or feature is targeted.");
    if (status === "ready") {
      status = "needs_clarification";
    }
  }

  if (!hasEnoughContext(query, state.contextPack)) {
    reasons.push("Task may not provide enough repository context for confident planning.");
    if (status === "ready") {
      status = "needs_clarification";
    }
  }

  if (isUnsafeWriteIntent(query)) {
    blockers.push("Request appears unsafe or destructive.");
    status = "unsafe";
  }

  if (status === "ready") {
    reasons.push("Task appears clear, supported, and safely scoped for this run.");
  } else if (status === "needs_clarification") {
    warnings.push("Task is likely actionable but needs better context before execution.");
  }

  return {
    status,
    reasons,
    blockers,
    warnings,
  };
}

function readinessSeverity(status: ReadinessGateStatus): "info" | "warning" | "error" {
  switch (status) {
    case "ready":
      return "info";
    case "needs_clarification":
      return "warning";
    default:
      return "error";
  }
}

function isRepoRelativePathLike(rawPath: string): string | null {
  const normalizedInput = rawPath.trim().replace(/\\/g, "/");
  if (!normalizedInput.length) {
    return null;
  }
  if (normalizedInput.includes("\0") || /[<>:"|?*]/.test(normalizedInput)) {
    return null;
  }
  if (normalizedInput.startsWith(".") && normalizedInput !== "." && normalizedInput.startsWith("../")) {
    return null;
  }
  if (path.win32.isAbsolute(normalizedInput) || path.posix.isAbsolute(normalizedInput)) {
    return null;
  }
  if (normalizedInput.includes(" ")) {
    return null;
  }
  if (!/[A-Za-z0-9_./@-]/.test(normalizedInput)) {
    return null;
  }

  const normalized = path.posix.normalize(normalizedInput);
  const segments = normalized.split("/");
  if (segments.some((segment) => UNCLOSED_PATH_SEGMENTS.has(segment))) {
    return null;
  }
  if (segments.includes("..") || normalized.startsWith("../") || normalized.startsWith("./")) {
    return null;
  }
  return normalized;
}

function toAbsolutePath(repoRoot: string, normalizedPath: string): string {
  return path.resolve(repoRoot, normalizedPath);
}

function isRepoPathWithinRoot(repoRoot: string, candidate: string): boolean {
  const absolute = toAbsolutePath(repoRoot, candidate);
  const relative = path.relative(repoRoot, absolute);
  return relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative);
}

function isAllowedCandidateSegment(segment: string): boolean {
  return !SCAN_IGNORED_DIRS.has(segment) && segment !== ".codepawl" && segment !== ".git";
}

function isAllowedPathByRepoRules(repoRoot: string, candidate: string): boolean {
  const normalized = isRepoRelativePathLike(candidate);
  if (!normalized) {
    return false;
  }
  if (!isRepoPathWithinRoot(repoRoot, normalized)) {
    return false;
  }
  const segments = normalized.split("/");
  if (segments.some((segment) => !isAllowedCandidateSegment(segment))) {
    return false;
  }
  if (isBinaryFilePath(normalized) || isSecretFile(normalized)) {
    return false;
  }
  return true;
}

function shouldFailUngrounded(total: number, rejected: number): boolean {
  if (total <= 0) {
    return false;
  }
  if (rejected >= MAX_UNGROUNDED_ABSOLUTE) {
    return true;
  }
  return rejected / total >= MAX_UNGROUNDED_RATIO;
}

function isLikelyFileDescription(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) {
    return true;
  }
  if (trimmed.includes(" ")) {
    return true;
  }
  return !/^[A-Za-z0-9._\-\/]+$/.test(trimmed);
}

function isTestFilePath(filePath: string): boolean {
  const normalized = path.posix.normalize(filePath.replace(/\\/g, "/"));
  const segments = normalized.split("/");
  const baseName = segments[segments.length - 1] ?? "";
  const lowered = baseName.toLowerCase();
  if (!/\.[A-Za-z0-9]+$/.test(baseName)) {
    return false;
  }
  const hasTestDir = segments.some((segment) => TEST_DIR_SEGMENTS.has(segment));
  const hasTestToken = lowered.includes("test") || lowered.includes("spec");
  const isAllowedExtension = /\.(ts|tsx|js|jsx|py|rs|go|java|cpp|c|cs|sh|md|yml|yaml|json|txt)$/.test(baseName);
  const stem = lowered.replace(/\.[a-z0-9]+$/, "");
  const hasTestStemToken = stem === "test" || stem === "spec"
    || stem.includes(".test")
    || stem.includes(".spec")
    || /(?:\.|_|-)test(?:\.|$)/.test(stem)
    || /(?:\.|_|-)spec(?:\.|$)/.test(stem);
  return isAllowedExtension && hasTestToken && (hasTestDir || hasTestStemToken);
}

function isNearRelevantModule(filePath: string, affectedModules: ReadonlyArray<string>): boolean {
  if (affectedModules.length === 0) {
    return false;
  }
  return affectedModules.some((modulePath) => {
    const normalizedModule = path.posix.normalize(modulePath.replace(/\\/g, "/"));
    if (!normalizedModule || normalizedModule === ".") {
      return false;
    }
    return filePath === normalizedModule || filePath.startsWith(`${normalizedModule}/`);
  });
}

function isAllowedNewTestFile(
  filePath: string,
  repoRoot: string,
  affectedModules: ReadonlyArray<string>
): boolean {
  if (!isAllowedPathByRepoRules(repoRoot, filePath)) {
    return false;
  }
  if (!isTestFilePath(filePath)) {
    return false;
  }
  return affectedModules.length === 0 || isNearRelevantModule(filePath, affectedModules);
}

function buildGeneratedByOpenpawlHeader(taskDescription: string | undefined): string {
  const normalized = taskDescription?.trim();
  if (normalized) {
    return `// ${GENERATED_BY_OPENPAWL_COMMENT}\n// Task: ${normalized}\n`;
  }
  return `// ${GENERATED_BY_OPENPAWL_COMMENT}\n`;
}

function sanitizeTestName(value: string): string {
  return value.trim().replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function buildVitestScaffold(filePath: string, description: string): string {
  const testName = sanitizeTestName(description || `Placeholder tests for ${filePath}`);
  const header = buildGeneratedByOpenpawlHeader(description);
  return `${header}
import { describe, it, expect } from "vitest";

describe("${sanitizeTestName(filePath)}", () => {
  it("${testName}", () => {
    expect(true).toBe(true);
  });
});
`;
}

function buildGenericTestFileContent(filePath: string, description: string): string {
  return `${buildGeneratedByOpenpawlHeader(description)}export {};\n`;
}

function buildTestFileContent(filePath: string, description: string): string {
  const ext = path.extname(filePath).toLowerCase().replace(/^\./, "");
  if (ext === "ts" || ext === "tsx") {
    return buildVitestScaffold(filePath, description);
  }

  if (ext === "js" || ext === "jsx") {
    return buildVitestScaffold(filePath, description);
  }

  return buildGenericTestFileContent(filePath, description);
}

function extractFallbackCandidateFiles(
  candidateFiles: ReadonlyArray<string>,
  repoRoot: string,
  affectedModules: ReadonlyArray<string>,
  exclude: ReadonlySet<string>,
  limit = 2,
  preferTestFiles = false
): string[] {
  const filtered = candidateFiles.filter(
    (candidatePath) => !exclude.has(candidatePath) && isAllowedPathByRepoRules(repoRoot, candidatePath)
  );

  if (preferTestFiles) {
    const testCandidates = filtered.filter(
      (candidatePath) => isTestFilePath(candidatePath)
        && (affectedModules.length === 0 || isNearRelevantModule(candidatePath, affectedModules))
    );
    if (testCandidates.length > 0) {
      return testCandidates.slice(0, limit);
    }
  }

  const relevantCandidates = filtered.filter(
    (candidatePath) => affectedModules.length === 0 || isNearRelevantModule(candidatePath, affectedModules)
  );
  if (relevantCandidates.length > 0) {
    return relevantCandidates.slice(0, limit);
  }

  return filtered.slice(0, limit);
}

async function resolveContextPack(state: AgentState): Promise<ContextPack> {
  if (state.contextPack) {
    return state.contextPack;
  }
  if (!state.repoScanResult) {
    throw new Error("ContextPack requires repoScanResult from the repo_scan node.");
  }

  return createContextPack({
    workspaceRoot: state.context.workspaceDir,
    task: state.query,
    repoScan: state.repoScanResult,
    maxFiles: state.context.contextMaxFiles,
    maxBytes: state.context.contextMaxBytes,
      maxChars: state.context.contextMaxChars,
    testCommand: state.context.testCommand,
  });
}

interface GroundedScopeResult {
  readonly accepted: {
    readonly proposedFilesToModify: string[];
    readonly proposedFilesToCreate: string[];
  };
  readonly rejected: {
    readonly proposedFilesToModify: ReadonlyArray<{ readonly file: string; readonly reason: string }>;
    readonly proposedFilesToCreate: ReadonlyArray<{ readonly file: string; readonly reason: string }>;
  };
  readonly groundingNotes: string[];
  readonly fallbackUsed: boolean;
  readonly fallbackFiles: ReadonlyArray<string>;
  readonly shouldFail: boolean;
  readonly failureReason: string | null;
}

function applyScopeGrounding(
  state: AgentState,
  scopeAnalysisResult: ScopeAnalysisResult,
  contextPack: ContextPack
): GroundedScopeResult {
  const repoRoot = state.context.workspaceDir;
  const repoFiles = new Set(
    (state.repoScanResult?.files ?? [])
      .filter((file) => !file.isDir)
      .map((file) => file.path)
  );
  const candidateSet = new Set(contextPack.candidateFiles);
  const groundingNotes: string[] = [];
  const rejectedModify: { file: string; reason: string }[] = [];
  const rejectedCreate: { file: string; reason: string }[] = [];
  const acceptedModify: string[] = [];
  const acceptedCreate: string[] = [];
  const isTestTask = /(\btest\b|\btests\b)/i.test(state.query);
  const fallbackLimit = 2;
  let fallbackFiles: string[] = [];

  const addIfGrounded = (
    rawPath: string,
    kind: "modify" | "create"
  ): void => {
    if (isLikelyFileDescription(rawPath)) {
      (kind === "modify" ? rejectedModify : rejectedCreate).push({
        file: rawPath,
        reason: "value does not look like a repo-relative file path",
      });
      return;
    }

    const pathReason = isRepoRelativePathLike(rawPath);
    if (!pathReason) {
      (kind === "modify" ? rejectedModify : rejectedCreate).push({
        file: rawPath,
        reason: "path is not a valid repo-relative file path",
      });
      return;
    }
    const normalizedPath = pathReason;
    if (!isAllowedPathByRepoRules(repoRoot, normalizedPath)) {
      (kind === "modify" ? rejectedModify : rejectedCreate).push({
        file: rawPath,
        reason: "path is outside repository root or not allowed",
      });
      return;
    }

    if (repoFiles.has(normalizedPath) || candidateSet.has(normalizedPath)) {
      (kind === "modify" ? acceptedModify : acceptedCreate).push(normalizedPath);
      return;
    }

    if (
      kind === "create" &&
      (isTestTask
        ? isAllowedNewTestFile(
          normalizedPath,
          repoRoot,
          scopeAnalysisResult.affectedModules
        )
        : isAllowedPathByRepoRules(repoRoot, normalizedPath))
    ) {
      acceptedCreate.push(normalizedPath);
      return;
    }

    (kind === "modify" ? rejectedModify : rejectedCreate).push({
      file: rawPath,
      reason: "path is not present in repo scan and not an accepted new path",
    });
  };

  scopeAnalysisResult.proposedFilesToModify.forEach((p) => addIfGrounded(p, "modify"));
  scopeAnalysisResult.proposedFilesToCreate.forEach((p) => addIfGrounded(p, "create"));

  const totalProposals =
    scopeAnalysisResult.proposedFilesToModify.length + scopeAnalysisResult.proposedFilesToCreate.length;
  const totalRejected = rejectedModify.length + rejectedCreate.length;
  const hasAcceptedCandidates = acceptedModify.length + acceptedCreate.length > 0;
  const canFallback = state.context.dryRun && totalRejected > 0;
  const fallbackUsed = canFallback && !hasAcceptedCandidates;
  const fallbackExclude = new Set([
    ...acceptedModify,
    ...acceptedCreate,
    ...rejectedModify.map((item) => item.file),
    ...rejectedCreate.map((item) => item.file),
  ]);

  if (fallbackUsed) {
    fallbackFiles = extractFallbackCandidateFiles(
      contextPack.candidateFiles,
      repoRoot,
      scopeAnalysisResult.affectedModules,
      fallbackExclude,
      fallbackLimit,
      isTestTask
    );
    for (const fallback of fallbackFiles) {
      acceptedModify.push(fallback);
      groundingNotes.push(`Fallback: using existing relevant context file from context pack: ${fallback}`);
    }
  }

  for (const item of rejectedModify) {
    groundingNotes.push(`Rejected scope modify proposal: ${item.file} (${item.reason})`);
  }
  for (const item of rejectedCreate) {
    groundingNotes.push(`Rejected scope create proposal: ${item.file} (${item.reason})`);
  }

  return {
    accepted: {
      proposedFilesToModify: acceptedModify,
      proposedFilesToCreate: acceptedCreate,
    },
    rejected: {
      proposedFilesToModify: rejectedModify,
      proposedFilesToCreate: rejectedCreate,
    },
    groundingNotes,
    fallbackUsed,
    fallbackFiles,
    shouldFail: !state.context.dryRun && shouldFailUngrounded(totalProposals, totalRejected),
    failureReason: shouldFailUngrounded(totalProposals, totalRejected)
      ? `rejected proposal count=${totalRejected} out of ${totalProposals}`
      : null,
  };
}

interface GroundedPatchResult {
  readonly acceptedChunks: PatchPlan["chunks"];
  readonly rejectedChunks: ReadonlyArray<{ index: number; file: string; reason: string }>;
  readonly groundingNotes: string[];
}

type PatchChunk = PatchPlan["chunks"][number];

function applyPatchGrounding(
  state: AgentState,
  patchPlan: PatchPlan,
  contextPack: ContextPack
): GroundedPatchResult {
  const repoRoot = state.context.workspaceDir;
  const repoFiles = new Set(
    (state.repoScanResult?.files ?? [])
      .filter((file) => !file.isDir)
      .map((file) => file.path)
  );
  const groundingNotes: string[] = [];
  const acceptedChunks: PatchChunk[] = [];
  const rejectedChunks: { index: number; file: string; reason: string }[] = [];
  const affectedModules = state.scopeAnalysisResult?.affectedModules ?? [];

  patchPlan.chunks.forEach((chunk, index) => {
    if (isLikelyFileDescription(chunk.file)) {
      rejectedChunks.push({
        index,
        file: chunk.file,
        reason: "chunk file does not look like a repo-relative file path",
      });
      return;
    }

    const normalizedPath = isRepoRelativePathLike(chunk.file);
    if (!normalizedPath) {
      rejectedChunks.push({
        index,
        file: chunk.file,
        reason: "chunk file is not a repo-relative path",
      });
      return;
    }
    if (!isAllowedPathByRepoRules(repoRoot, normalizedPath)) {
      rejectedChunks.push({
        index,
        file: chunk.file,
        reason: "chunk file is outside repo root or uses disallowed path",
      });
      return;
    }
    if (repoFiles.has(normalizedPath)) {
      acceptedChunks.push({
        ...chunk,
        file: normalizedPath,
      });
      return;
    }
    if (chunk.type === "create" && isAllowedNewTestFile(normalizedPath, repoRoot, affectedModules)) {
      acceptedChunks.push({
        ...chunk,
        file: normalizedPath,
      });
      return;
    }
    rejectedChunks.push({
      index,
      file: chunk.file,
      reason: "chunk file was neither an existing repo file nor a plausible new test file",
    });
  });

  const totalChunks = patchPlan.chunks.length;
  const totalRejected = rejectedChunks.length;
  if (shouldFailUngrounded(totalChunks, totalRejected)) {
    groundingNotes.push(`Ungrounded patch chunks: ${totalRejected} of ${totalChunks} were rejected.`);
    throw new ProviderJsonOutputError(
      {
        provider: state.context.providerName ?? "mock",
        model: state.context.modelName ?? "deterministic-mock",
        purpose: "patch_plan",
      },
      "ungrounded_provider_output",
      "Ungrounded patch chunks were rejected as not repo-grounded.",
      `rejected chunk count=${totalRejected} out of ${totalChunks}`,
      null,
      0,
      {
        retryAttempt: 0,
        retryAttempted: false,
        retrySucceeded: false,
      }
    );
  }

  for (const rejected of rejectedChunks) {
    groundingNotes.push(`Rejected patch chunk: ${rejected.file} (#${rejected.index}, ${rejected.reason})`);
  }

  return {
    acceptedChunks,
    rejectedChunks,
    groundingNotes,
  };
}

function summarizePatchSelectionForPrompt(files: ReadonlyArray<{ path: string; reason: string; content: string }>): Array<{
  readonly file: string;
  readonly reason: string;
  readonly chars: number;
  readonly excerpt: string;
}> {
  return files.map((file) => {
    const excerpt = file.content
      ? `${file.content.replace(/\s+/g, " ").trim().slice(0, PATCH_FILE_EXCERPT_CHARS)}...`
      : "";
    return {
      file: file.path,
      reason: file.reason,
      chars: file.content.length,
      excerpt,
    };
  });
}

function normalizeValidationPath(candidate: string): string {
  return path.posix.normalize(candidate.replace(/\\/g, "/"))
    .replace(/^\.?\//, "")
    .replace(/\/$/, "");
}

function collectValidationInferencePaths(state: AgentState): ReadonlyArray<string> {
  const paths = new Set<string>();

  // Priority 1: use files actually created/applied in this run.
  for (const file of state.writeResult?.created ?? []) {
    paths.add(normalizeValidationPath(file));
  }

  // Priority 2: use patch plan chunk targets.
  for (const chunk of state.patchPlan?.chunks ?? []) {
    paths.add(normalizeValidationPath(chunk.file));
  }

  // Priority 3: use selected files as the final scoped fallback.
  if (state.fileSelectionResult?.selectedFiles) {
    for (const file of state.fileSelectionResult.selectedFiles) {
      paths.add(normalizeValidationPath(file.path));
    }
  }

  return Array.from(paths);
}

function collectScannedPackageRoots(state: AgentState): ReadonlySet<string> {
  const packageRoots = new Set<string>();
  if (!state.repoScanResult) {
    return packageRoots;
  }

  for (const packageConfig of state.repoScanResult.packageConfigs) {
    if (packageConfig.type !== "npm") {
      continue;
    }
    const packageDir = path.dirname(packageConfig.path);
    packageRoots.add(normalizeValidationPath(packageDir));
  }

  return packageRoots;
}

type ValidationDecisionSource = "explicit" | "inferred" | "placeholder" | "unavailable";

interface ValidationDecisionPayload {
  readonly source: ValidationDecisionSource;
  readonly confidence: number;
  readonly reason: string;
  readonly command: string;
}

function inferScopedValidationCommand(
  state: AgentState,
  paths: ReadonlyArray<string>
): ValidationDecisionPayload | null {
  const evidence = new Map<string, { confidence: number; reasons: string[] }>();
  const packageRoots = collectScannedPackageRoots(state);

  for (const candidate of paths) {
    const normalized = normalizeValidationPath(candidate);

    for (const rule of SCOPED_VALIDATION_COMMANDS) {
      if (!packageRoots.has(rule.pathPrefix)) {
        continue;
      }

      const matchesRule = normalized === rule.pathPrefix
        || normalized.startsWith(`${rule.pathPrefix}/`)
        || normalized === `${rule.pathPrefix}/package.json`
        || normalized.endsWith(`/${rule.pathPrefix}`);

      if (!matchesRule) {
        continue;
      }

      const existing = evidence.get(rule.command) ?? { confidence: 0, reasons: [] };
      const repeatCount = existing.reasons.length;
      const updatedConfidence = Math.min(1, rule.confidence + (repeatCount * 0.02));
      evidence.set(rule.command, {
        confidence: updatedConfidence,
        reasons: [...existing.reasons, `${candidate} -> ${rule.id}`],
      });
    }
  }

  if (evidence.size === 0) {
    return null;
  }

  const sorted = Array.from(evidence.entries())
    .map(([command, info]) => ({
      command,
      confidence: Math.min(1, info.confidence),
      reason: `Inferred from scoped paths: ${info.reasons.join(", ")}`,
    }))
    .sort((lhs, rhs) => (rhs.confidence - lhs.confidence) || lhs.command.localeCompare(rhs.command));

  const best = sorted[0];
  if (!best) {
    return null;
  }

  return {
    source: "inferred",
    confidence: best.confidence,
    reason: best.reason,
    command: best.command,
  };
}

function resolveValidationDecision(state: AgentState): ValidationDecisionPayload {
  if (state.context.testCommand) {
    return {
      source: "explicit",
      confidence: 1,
      reason: "Explicit --test-cmd value was provided.",
      command: state.context.testCommand,
    };
  }

  const inferred = inferScopedValidationCommand(state, collectValidationInferencePaths(state));
  if (inferred) {
    if (!state.context.dryRun && inferred.confidence < WRITE_MODE_MIN_VALIDATION_CONFIDENCE) {
      return {
        source: "unavailable",
        confidence: VALIDATION_DECISION_UNAVAILABLE_CONFIDENCE,
        reason: `Inferred validation command confidence (${inferred.confidence}) was below write-mode threshold (${WRITE_MODE_MIN_VALIDATION_CONFIDENCE}).`,
        command: "",
      };
    }
    return inferred;
  }

  if (state.context.dryRun) {
    return {
      source: "placeholder",
      confidence: 1,
      reason: "No explicit or inferred scoped validation command was found; using dry-run placeholder.",
      command: PLACEHOLDER_VALIDATION_COMMAND,
    };
  }

  return {
    source: "unavailable",
    confidence: VALIDATION_DECISION_UNAVAILABLE_CONFIDENCE,
    reason: "No explicit or inferred scoped validation command was found and write mode requires a safe validation command.",
    command: "",
  };
}

function isPlaceholderValidationCommand(command: string): boolean {
  return command === PLACEHOLDER_VALIDATION_COMMAND;
}

function providerPayload(
  state: AgentState,
  llm: LlmProvider,
  purpose: string,
  messages?: ReadonlyArray<{ content: string }>,
  responseFormat: "json_schema" | "json_object" = "json_schema",
  maxTokens?: number
): Record<string, unknown> {
  return {
    provider: llm.providerName,
    model: llm.modelName,
    purpose,
    responseFormat,
    responseFormatRequested: responseFormat === "json_object" || responseFormat === "json_schema",
    responseFormatType: responseFormat,
    maxTokens: maxTokens ?? null,
    promptChars: messages ? sanitizeForPromptMetrics(messages) : 0,
    ...(state.context.includePromptMetadata && messages
      ? { promptMetadata: createPromptMetadata(messages) }
      : {}),
  };
}

function providerErrorPayload(
  llm: LlmProvider,
  purpose: string,
  err: unknown,
  tokenUsage?: { readonly inputTokens: number; readonly outputTokens: number },
  finishReason?: string,
  contentLength?: number,
  responseFormatRequested: boolean = true,
  responseFormat: "json_schema" | "json_object" = "json_schema",
  retryAttempt: number = 0,
  retryAttempted: boolean = false,
  retrySucceeded: boolean = false,
  responseShape?: {
    readonly hasContent: boolean;
    readonly hasReasoningContent: boolean;
    readonly contentLength: number;
    readonly reasoningContentLength: number;
  }
): Record<string, unknown> {
  const parseCategory = err instanceof ProviderJsonOutputError
    ? err.category
    : err instanceof ProviderResponseShapeError
      ? err.issue
      : "unknown";
  return {
    provider: llm.providerName,
    model: llm.modelName,
    purpose,
    parseCategory,
    schemaValidationPath: err instanceof ProviderJsonOutputError ? err.schemaValidationPath : null,
    validationStatus: err instanceof ProviderJsonOutputError && err.category === "schema_validation"
      ? "schema_invalid"
      : "parse_invalid",
    contentPreview: err instanceof ProviderJsonOutputError ? err.preview : null,
    finishReason: finishReason ?? (err instanceof ProviderJsonOutputError ? err.finishReason ?? null : null),
    contentLength: contentLength ?? (err instanceof ProviderJsonOutputError ? err.contentLength : null),
    responseShape: responseShape ?? null,
    responseFormatRequested,
    responseFormatType: responseFormat,
    retryAttempt,
    retryAttempted,
    retrySucceeded,
    error: err instanceof Error ? err.message : String(err),
    tokenUsage: tokenUsage ?? null,
  };
}

function isStructuredRetryable(err: unknown): err is ProviderJsonOutputError {
  return err instanceof ProviderJsonOutputError &&
    (err.category === "malformed_json" ||
      err.category === "non_json_output" ||
      err.category === "provider_reasoning_without_content" ||
      err.category === "schema_validation");
}

function mapProviderShapeError(
  llm: LlmProvider,
  purpose: "scope_analysis" | "patch_plan",
  err: ProviderResponseShapeError
): ProviderJsonOutputError {
  const category = err.issue === "provider_reasoning_without_content"
    ? "provider_reasoning_without_content"
    : "empty_content";

  return new ProviderJsonOutputError(
    {
      provider: llm.providerName,
      model: llm.modelName,
      purpose,
    },
    category,
    "",
    err.message,
    null,
    err.responseShape.contentLength
  );
}

interface StructuredRetryMetadata {
  readonly retryAttempt: number;
  readonly retryAttempted: boolean;
  readonly retrySucceeded: boolean;
}

function cloneProviderJsonOutputError(
  err: ProviderJsonOutputError,
  metadata: StructuredRetryMetadata
): ProviderJsonOutputError {
  return new ProviderJsonOutputError(
    {
      provider: err.provider,
      model: err.model,
      purpose: err.purpose,
      finishReason: err.finishReason,
    },
    err.category,
    err.preview,
    err.detail,
    err.schemaValidationPath,
    err.contentLength,
    metadata
  );
}

function compactStructuredMessages(purpose: string, schema: Record<string, unknown>, previousError: ProviderJsonOutputError, taskSummary: unknown): AgentMessage[] {
  const now = new Date().toISOString();
  return [
    {
      id: crypto.randomUUID(),
      role: "system",
      content: `Return JSON object only. No markdown. No prose. Match this schema exactly: ${JSON.stringify(schema, null, 2)}`,
      timestamp: now,
    },
    {
      id: crypto.randomUUID(),
      role: "user",
      content: `Structured Output Retry\n${JSON.stringify({
        purpose,
        previousError: {
          category: previousError.category,
          schemaValidationPath: previousError.schemaValidationPath,
        },
        taskSummary,
      })}`,
      timestamp: now,
    },
  ];
}

async function generateStructuredWithRetry<T>(
  state: AgentState,
  llm: LlmProvider,
  purpose: "scope_analysis" | "patch_plan",
  messages: AgentMessage[],
  maxTokens: number,
  schema: Record<string, unknown>,
  responseFormat: "json_schema" | "json_object",
  retryTaskSummary: unknown,
  parse: (completion: LlmCompletionResult) => T
): Promise<{
  parsed: T;
  completion: LlmCompletionResult;
  retryAttempt: number;
  retryAttempted: boolean;
  retrySucceeded: boolean;
}> {
  const ledger = activeLedgers.get(state.context.sessionId);
  const options = {
    responseFormat: buildStructuredResponseFormatForSchema(
      purpose,
      responseFormat,
      schema
    ),
    temperature: state.context.temperature,
    maxTokens,
  };
  let firstCompletion: LlmCompletionResult;

  try {
    firstCompletion = await llm.generateCompletion(messages, options);
    if (ledger && firstCompletion.usage) {
      ledger.addTokenUsage(firstCompletion.usage.inputTokens, firstCompletion.usage.outputTokens);
    }
  } catch (err: unknown) {
    if (!(err instanceof ProviderResponseShapeError)) {
      throw err;
    }

    const shapedError = mapProviderShapeError(llm, purpose, err);
    if (!isStructuredRetryable(shapedError)) {
      throw shapedError;
    }

    const retryMessages = compactStructuredMessages(purpose, schema, shapedError, retryTaskSummary);
    if (ledger) {
      ledger.recordEvent("system", "provider_structured_retry", "warning", {
        ...providerErrorPayload(
          llm,
          purpose,
          shapedError,
          err.usage,
          undefined,
          err.responseShape.contentLength,
          true,
          responseFormat,
          1,
          true,
          false,
          err.responseShape
        ),
        retryPrompt: {
          messageCount: retryMessages.length,
          totalChars: retryMessages.reduce((sum, message) => sum + message.content.length, 0),
        },
      });
    }

    let retryCompletion: LlmCompletionResult;
    try {
      retryCompletion = await llm.generateCompletion(retryMessages, options);
    } catch (retryErr: unknown) {
      if (retryErr instanceof ProviderResponseShapeError) {
        const mappedRetry = mapProviderShapeError(llm, purpose, retryErr);
        if (ledger) {
          ledger.recordEvent("system", "provider_structured_retry_failed", "error", {
            ...providerErrorPayload(
              llm,
              purpose,
              mappedRetry,
              retryErr.usage,
              undefined,
              retryErr.responseShape.contentLength,
              true,
              responseFormat,
              1,
              true,
              false,
              retryErr.responseShape
            ),
            retryPrompt: {
              messageCount: retryMessages.length,
              totalChars: retryMessages.reduce((sum, message) => sum + message.content.length, 0),
            },
          });
        }

        throw cloneProviderJsonOutputError(mappedRetry, {
          retryAttempt: 1,
          retryAttempted: true,
          retrySucceeded: false,
        });
      }
      throw retryErr;
    }

    if (ledger && retryCompletion.usage) {
      ledger.addTokenUsage(retryCompletion.usage.inputTokens, retryCompletion.usage.outputTokens);
    }

    try {
      return {
        parsed: parse(retryCompletion),
        completion: retryCompletion,
        retryAttempt: 1,
        retryAttempted: true,
        retrySucceeded: true,
      };
    } catch (retryErr: unknown) {
      if (retryErr instanceof ProviderJsonOutputError) {
        if (ledger) {
          ledger.recordEvent("system", "provider_structured_retry_failed", "error", {
            ...providerErrorPayload(
              llm,
              purpose,
              retryErr,
              retryCompletion.usage,
              retryCompletion.finishReason,
              retryCompletion.content.length,
              true,
              responseFormat,
              1,
              true,
              false,
              retryCompletion.responseShape
            ),
            retryPrompt: {
              messageCount: retryMessages.length,
              totalChars: retryMessages.reduce((sum, message) => sum + message.content.length, 0),
            },
          });
        }

        throw cloneProviderJsonOutputError(retryErr, {
          retryAttempt: 1,
          retryAttempted: true,
          retrySucceeded: false,
        });
      }

      throw retryErr;
    }
  }

  try {
    return {
      parsed: parse(firstCompletion),
      completion: firstCompletion,
      retryAttempt: 0,
      retryAttempted: false,
      retrySucceeded: false,
    };
  } catch (err: unknown) {
    if (!(err instanceof ProviderJsonOutputError)) {
      throw err;
    }
    if (!isStructuredRetryable(err)) {
      throw cloneProviderJsonOutputError(err, {
        retryAttempt: 0,
        retryAttempted: false,
        retrySucceeded: false,
      });
    }

    const retryMessages = compactStructuredMessages(purpose, schema, err, retryTaskSummary);
    if (ledger) {
      ledger.recordEvent("system", "provider_structured_retry", "warning", {
        ...providerErrorPayload(
          llm,
          purpose,
          err,
          firstCompletion.usage,
          firstCompletion.finishReason,
          firstCompletion.content.length,
          true,
          responseFormat,
          1,
          true,
          false,
          firstCompletion.responseShape
        ),
        retryPrompt: {
          messageCount: retryMessages.length,
          totalChars: retryMessages.reduce((sum, message) => sum + message.content.length, 0),
        },
      });
    }

    let retryCompletion: LlmCompletionResult;
    try {
      retryCompletion = await llm.generateCompletion(retryMessages, options);
    } catch (retryErr: unknown) {
      if (retryErr instanceof ProviderResponseShapeError) {
        const mappedRetry = mapProviderShapeError(llm, purpose, retryErr);
        if (ledger) {
          ledger.recordEvent("system", "provider_structured_retry_failed", "error", {
            ...providerErrorPayload(
              llm,
              purpose,
              mappedRetry,
              retryErr.usage,
              undefined,
              retryErr.responseShape.contentLength,
              true,
              responseFormat,
              1,
              true,
              false,
              retryErr.responseShape
            ),
            retryPrompt: {
              messageCount: retryMessages.length,
              totalChars: retryMessages.reduce((sum, message) => sum + message.content.length, 0),
            },
          });
        }

        throw cloneProviderJsonOutputError(mappedRetry, {
          retryAttempt: 1,
          retryAttempted: true,
          retrySucceeded: false,
        });
      }
      throw retryErr;
    }

    if (ledger && retryCompletion.usage) {
      ledger.addTokenUsage(retryCompletion.usage.inputTokens, retryCompletion.usage.outputTokens);
    }

    try {
      return {
        parsed: parse(retryCompletion),
        completion: retryCompletion,
        retryAttempt: 1,
        retryAttempted: true,
        retrySucceeded: true,
      };
    } catch (retryErr: unknown) {
      if (retryErr instanceof ProviderJsonOutputError) {
        if (ledger) {
          ledger.recordEvent("system", "provider_structured_retry_failed", "error", {
            ...providerErrorPayload(
              llm,
              purpose,
              retryErr,
              retryCompletion.usage,
              retryCompletion.finishReason,
              retryCompletion.content.length,
              true,
              responseFormat,
              1,
              true,
              false,
              retryCompletion.responseShape
            ),
            retryPrompt: {
              messageCount: retryMessages.length,
              totalChars: retryMessages.reduce((sum, message) => sum + message.content.length, 0),
            },
          });
        }

        throw cloneProviderJsonOutputError(retryErr, {
          retryAttempt: 1,
          retryAttempted: true,
          retrySucceeded: false,
        });
      }

      throw retryErr;
    }
  }
}

export function createIntakeNode(): AgentNode {
  return async (state) => {
    const messages = [...state.messages];
    if (messages.length === 0) {
      messages.push({
        id: crypto.randomUUID(),
        role: "user",
        content: state.query,
        timestamp: new Date().toISOString(),
      });
    }
    return {
      messages,
    };
  };
}

export function createReadinessGateNode(): AgentNode {
  return async (state) => {
    const ledger = activeLedgers.get(state.context.sessionId);
    const readiness = evaluateReadiness(state);

    if (ledger) {
      ledger.recordEvent("system", "readiness_gate", readinessSeverity(readiness.status), {
        status: readiness.status,
        reasons: readiness.reasons,
        blockers: readiness.blockers,
        warnings: readiness.warnings,
        writeMode: state.context.dryRun ? "dry-run" : "write",
      });
    }

    if (
      readiness.status === "unsupported" ||
      readiness.status === "unsafe" ||
      readiness.status === "needs_clarification"
    ) {
      const blockingReasons = readiness.blockers.length > 0
        ? readiness.blockers
        : readiness.reasons;
      return {
        readinessGateResult: readiness,
        error: `Readiness gate blocked this run: ${readiness.status}${blockingReasons.length > 0 ? ` - ${blockingReasons.join("; ")}` : ""}`,
      };
    }

    return {
      readinessGateResult: readiness,
    };
  };
}

export function createRepoScanNode(): AgentNode {
  return async (state) => {
    const workspaceDir = state.context.workspaceDir;
    const ledger = activeLedgers.get(state.context.sessionId);

    let fileCount = 0;

    async function scanDirectory(
      dir: string,
      rootDir: string
    ): Promise<{ path: string; sizeBytes: number; isDir: boolean }[]> {
      if (fileCount >= SCAN_MAX_FILES) return [];
      const results: { path: string; sizeBytes: number; isDir: boolean }[] = [];
      let entries: ReturnType<typeof Object.create> = [];
      try {
        entries = await fs.readdir(dir, { withFileTypes: true });
      } catch {
        return results;
      }
      for (const entry of entries) {
        if (fileCount >= SCAN_MAX_FILES) break;
        const fullPath = path.join(dir, entry.name);
        const relativePath = path.relative(rootDir, fullPath);

        if (SCAN_IGNORED_DIRS.has(entry.name)) {
          continue;
        }

        // Skip secret files during scan
        if (!entry.isDirectory() && isSecretFile(entry.name)) {
          if (ledger) {
            ledger.recordEvent("system", `skipped_secret_file:${relativePath}`, "warning", {
              reason: "secret file excluded from scan",
            });
          }
          continue;
        }

        if (entry.isDirectory()) {
          results.push({
            path: relativePath,
            sizeBytes: 0,
            isDir: true,
          });
          const subResults = await scanDirectory(fullPath, rootDir);
          results.push(...subResults);
        } else if (entry.isFile()) {
          let size = 0;
          try {
            const stat = await fs.stat(fullPath);
            size = stat.size;
          } catch { /* ignore stat errors */ }
          results.push({
            path: relativePath,
            sizeBytes: size,
            isDir: false,
          });
          fileCount++;
        }
      }
      return results;
    }

    const files = await scanDirectory(workspaceDir, workspaceDir);

    if (ledger) {
      ledger.recordEvent("system", "repo_scan_complete", "info", {
        fileCount: files.filter((f) => !f.isDir).length,
        dirCount: files.filter((f) => f.isDir).length,
        cappedAt: fileCount >= SCAN_MAX_FILES ? SCAN_MAX_FILES : null,
      });
    }

    const extMap: Record<string, string> = {
      ".ts": "TypeScript",
      ".tsx": "TypeScript",
      ".js": "JavaScript",
      ".jsx": "JavaScript",
      ".py": "Python",
      ".rs": "Rust",
      ".go": "Go",
      ".java": "Java",
      ".cpp": "C++",
      ".c": "C",
      ".h": "C/C++",
      ".cs": "C#",
      ".sh": "Shell",
    };

    const detectedLanguagesSet = new Set<string>();
    for (const file of files) {
      if (file.isDir) continue;
      const ext = path.extname(file.path);
      const lang = extMap[ext];
      if (lang) {
        detectedLanguagesSet.add(lang);
      }
    }
    const detectedLanguages = Array.from(detectedLanguagesSet);

    const packageConfigs: { type: "npm" | "pip" | "cargo" | "other"; path: string }[] = [];
    for (const file of files) {
      if (file.isDir) continue;
      const filename = path.basename(file.path);
      if (filename === "package.json") {
        packageConfigs.push({ type: "npm", path: file.path });
      } else if (
        filename === "pyproject.toml" ||
        filename === "requirements.txt" ||
        filename === "Pipfile"
      ) {
        packageConfigs.push({ type: "pip", path: file.path });
      } else if (filename === "Cargo.toml") {
        packageConfigs.push({ type: "cargo", path: file.path });
      }
    }

    const repoScanResult: RepoScanResult = {
      rootDir: workspaceDir,
      files,
      detectedLanguages,
      packageConfigs,
    };

  const contextPack = await createContextPack({
      workspaceRoot: workspaceDir,
      task: state.query,
      repoScan: repoScanResult,
      maxFiles: state.context.contextMaxFiles,
      maxBytes: state.context.contextMaxBytes,
      maxChars: state.context.contextMaxChars,
      testCommand: state.context.testCommand,
      safetyExclusions: [
        `ignored directories: ${Array.from(SCAN_IGNORED_DIRS).sort().join(", ")}`,
        "secret-like files excluded from repo scan",
        "binary-like files excluded from compaction",
        ...state.context.testCommand ? [`test command: ${state.context.testCommand}`] : [],
      ],
    });

    if (ledger) {
      ledger.recordEvent("system", "context_pack_created", "info", {
        inputScannedFiles: contextPack.metrics.inputScannedFiles,
        candidateFiles: contextPack.metrics.candidateFiles,
        includedFiles: contextPack.metrics.includedFiles,
        omittedFiles: contextPack.metrics.omittedFiles,
        scannedBytes: contextPack.metrics.scannedBytes,
        includedBytes: contextPack.metrics.includedBytes,
        omittedBytes: contextPack.metrics.omittedBytes,
        estimatedContextChars: contextPack.metrics.estimatedContextChars,
        compactionReason: contextPack.metrics.compactionReason,
        budget: contextPack.budget,
        compacted: contextPack.metrics.compactionReason !== "none",
      });
    }

    return {
      repoScanResult,
      contextPack,
    };
  };
}

export function createScopeAnalysisNode(llm: LlmProvider): AgentNode {
  return async (state) => {
    const ledger = activeLedgers.get(state.context.sessionId);

    if (isReviewOnlyTask(state.query)) {
      const changedFiles = process.env["CODEPAWL_CHANGED_FILES"]
        ?.split(/\r?\n/)
        .map((file) => file.trim())
        .filter(Boolean) ?? [];
      const scopeAnalysisResult: ScopeAnalysisResult = {
        rationale: changedFiles.length > 0
          ? "Review-only task detected. Scope is limited to changed files provided by the current context."
          : "Review-only task detected. No changed files available in current context.",
        affectedModules: changedFiles.length > 0 ? changedFiles : ["No changed files available in current context"],
        proposedFilesToModify: changedFiles,
        proposedFilesToCreate: [],
      };

      if (ledger) {
        ledger.recordEvent("system", "review_only_scope", "info", {
          changedFileCount: changedFiles.length,
        });
      }

      return {
        scopeAnalysisResult,
        messages: [
          {
            id: crypto.randomUUID(),
            role: "assistant",
            content: `Scope Analysis:\nRationale: ${scopeAnalysisResult.rationale}\nProposed Files to Modify: ${scopeAnalysisResult.proposedFilesToModify.join(", ")}\nProposed Files to Create: `,
            timestamp: new Date().toISOString(),
          },
        ],
      };
    }

    const contextPack = await resolveContextPack(state);
    const compactContext = compactContextForPrompt(contextPack);
    const systemPrompt = `Return JSON object only. No markdown. No prose.
Schema: ${SCOPE_ANALYSIS_JSON_SCHEMA_PROMPT}
Example: {"rationale":"Add focused tests for trace ledger behavior.","affectedModules":["packages/core"],"proposedModifications":[],"proposedCreations":["packages/core/src/__tests__/trace-ledger.test.ts"]}`;
    const userMessage = `${SCOPE_CONTEXT_PROMPT_MARKER}:
${JSON.stringify({
  task: state.query,
  context: compactContext,
})}`;

    const messages: AgentMessage[] = [
      ...state.messages,
      {
        id: crypto.randomUUID(),
        role: "system",
        content: systemPrompt,
        timestamp: new Date().toISOString(),
      },
      {
        id: crypto.randomUUID(),
        role: "user",
        content: userMessage,
        timestamp: new Date().toISOString(),
      },
    ];

    const maxTokens = state.context.scopeAnalysisMaxTokens ?? DEFAULT_SCOPE_ANALYSIS_MAX_TOKENS;
    const responseFormat = resolveStructuredOutputFormatMode(state);

    if (ledger) {
      ledger.recordEvent(
        "llm_call",
        "scope_analysis",
        "info",
        providerPayload(state, llm, "scope_analysis", messages, responseFormat, maxTokens)
      );
    }

    let scopeAnalysisResult: ScopeAnalysisResult;
    let completion: LlmCompletionResult | undefined;
    let retryAttempt = 0;
    let retryAttempted = false;
    let retrySucceeded = false;
    try {
      const structured = await generateStructuredWithRetry(
        state,
        llm,
        "scope_analysis",
        messages,
        maxTokens,
        SCOPE_ANALYSIS_JSON_SCHEMA,
        responseFormat,
        {
          task: state.query,
          contextCandidateFiles: compactContext.candidateFiles.length,
          contextIncludedFiles: compactContext.compactFileSummaries.length,
          detectedLanguages: state.repoScanResult?.detectedLanguages ?? [],
        },
        (candidate) => parseScopeAnalysisResponse(candidate.content, {
          provider: llm.providerName,
          model: llm.modelName,
          purpose: "scope_analysis",
          finishReason: candidate.finishReason,
        })
      );
      scopeAnalysisResult = structured.parsed;
      completion = structured.completion;
      retryAttempt = structured.retryAttempt;
      retryAttempted = structured.retryAttempted;
      retrySucceeded = structured.retrySucceeded;
    const groundedScope = applyScopeGrounding(state, scopeAnalysisResult, contextPack);
    scopeAnalysisResult = {
      ...scopeAnalysisResult,
      proposedFilesToModify: groundedScope.accepted.proposedFilesToModify,
      proposedFilesToCreate: groundedScope.accepted.proposedFilesToCreate,
      groundingNotes: [
        ...(scopeAnalysisResult.groundingNotes ?? []),
        ...groundedScope.groundingNotes,
      ],
      groundingFallbackUsed: groundedScope.fallbackUsed,
      groundingFallbackFiles: groundedScope.fallbackFiles,
      rejectedProposedFilesToModify: groundedScope.rejected.proposedFilesToModify,
      rejectedProposedFilesToCreate: groundedScope.rejected.proposedFilesToCreate,
    };

    if (groundedScope.shouldFail) {
      const groundedError = new ProviderJsonOutputError(
        {
          provider: state.context.providerName ?? "mock",
          model: state.context.modelName ?? "deterministic-mock",
          purpose: "scope_analysis",
        },
        "ungrounded_provider_output",
        "Ungrounded path proposals were rejected as not repo-grounded.",
        groundedScope.failureReason ?? "rejected proposals exceeded safe grounding ratio",
        null,
        completion.content.length,
      );
      if (ledger) {
        ledger.recordEvent("tool_response", "scope_analysis_response", "error", {
          ...providerErrorPayload(
            llm,
            "scope_analysis",
            groundedError,
            completion.usage,
            completion.finishReason,
            completion.content.length,
            true,
            responseFormat,
            groundedError.retryAttempt,
            groundedError.retryAttempted,
            groundedError.retrySucceeded,
            completion.responseShape
          ),
          groundingNotes: groundedScope.groundingNotes,
          groundingFallbackUsed: groundedScope.fallbackUsed,
          groundingFallbackFiles: groundedScope.fallbackFiles,
          rejectedProposedFilesToModifyCount: groundedScope.rejected.proposedFilesToModify.length,
          rejectedProposedFilesToCreateCount: groundedScope.rejected.proposedFilesToCreate.length,
          tokenUsage: completion.usage ?? null,
        });
      }
      return {
        scopeAnalysisResult,
        error: groundedError.message,
        messages: [
          {
            id: crypto.randomUUID(),
            role: "assistant",
            content: `Scope Analysis:\nRationale: ${scopeAnalysisResult.rationale}\nProposed Files to Modify: ${scopeAnalysisResult.proposedFilesToModify.join(", ")}\nProposed Files to Create: ${scopeAnalysisResult.proposedFilesToCreate.join(", ")}`,
            timestamp: new Date().toISOString(),
          },
        ],
      };
    }

    if (ledger) {
      ledger.recordEvent("tool_response", "scope_analysis_response", "info", {
          provider: llm.providerName,
          model: llm.modelName,
          purpose: "scope_analysis",
          parseCategory: "ok",
          schemaValidationPath: null,
          validationStatus: "valid",
          finishReason: completion.finishReason ?? null,
          contentLength: completion.content.length,
          responseShape: completion.responseShape ?? null,
          responseFormatRequested: true,
          responseFormatType: responseFormat,
          retryAttempt,
          retryAttempted,
          retrySucceeded,
          groundingNotes: groundedScope.groundingNotes,
          groundingFallbackUsed: groundedScope.fallbackUsed,
          groundingFallbackFiles: groundedScope.fallbackFiles,
          rejectedProposedFilesToModifyCount: groundedScope.rejected.proposedFilesToModify.length,
          rejectedProposedFilesToCreateCount: groundedScope.rejected.proposedFilesToCreate.length,
          tokenUsage: completion.usage ?? null,
        });
      }
    } catch (err: unknown) {
      const providerError = err instanceof ProviderJsonOutputError
        ? err
        : null;
      if (ledger) {
        ledger.recordEvent(
          "tool_response",
          "scope_analysis_response",
          "error",
          providerErrorPayload(
            llm,
            "scope_analysis",
            err,
            completion?.usage,
            completion?.finishReason,
            completion?.content.length,
            true,
            responseFormat,
            providerError?.retryAttempt ?? retryAttempt,
            providerError?.retryAttempted ?? retryAttempted,
            providerError?.retrySucceeded ?? retrySucceeded,
            completion?.responseShape,
          )
        );
      }
      throw err;
    }

    return {
      scopeAnalysisResult,
      messages: [
        {
          id: crypto.randomUUID(),
          role: "assistant",
          content: `Scope Analysis:\nRationale: ${scopeAnalysisResult.rationale}\nProposed Files to Modify: ${scopeAnalysisResult.proposedFilesToModify.join(", ")}\nProposed Files to Create: ${scopeAnalysisResult.proposedFilesToCreate.join(", ")}`,
          timestamp: new Date().toISOString(),
        },
      ],
    };
  };
}

export function createFileSelectionNode(): AgentNode {
  return async (state) => {
    const selectedFiles: { path: string; reason: string; content: string }[] = [];
    const filesToRead = [
      ...(state.scopeAnalysisResult?.proposedFilesToModify ?? []),
      ...(state.scopeAnalysisResult?.proposedFilesToCreate ?? []),
    ];

    let totalBytesRead = 0;
    const ledger = activeLedgers.get(state.context.sessionId);

    for (const relPath of filesToRead) {
      // Skip secret files during selection
      if (isSecretFile(relPath)) {
        if (ledger) {
          ledger.recordEvent("system", `skipped_secret_file:${relPath}`, "warning", {
            reason: "secret file excluded from file selection",
          });
        }
        continue;
      }

      if (isBinaryFilePath(relPath)) {
        if (ledger) {
          ledger.recordEvent("system", `skipped_binary_file:${relPath}`, "warning", {
            reason: "binary file excluded from file selection",
          });
        }
        continue;
      }

      const fullPath = path.join(state.context.workspaceDir, relPath);
      let content = "";
      try {
        const stat = await fs.stat(fullPath);
        if (!stat.isFile()) {
          if (ledger) {
            ledger.recordEvent("system", `skipped_non_file:${relPath}`, "warning", {
              reason: "path is not a regular file",
            });
          }
          continue;
        }
        if (totalBytesRead + stat.size > SCAN_MAX_BYTES) {
          if (ledger) {
            ledger.recordEvent("system", `skipped_file_byte_cap:${relPath}`, "warning", {
              reason: "byte cap reached",
              totalBytesRead,
              fileSize: stat.size,
            });
          }
          break;
        }
        content = await fs.readFile(fullPath, "utf-8");
        totalBytesRead += stat.size;
      } catch (err: unknown) {
        const errorCode = typeof err === "object" && err !== null && "code" in err
          ? String((err as { code?: unknown }).code)
          : null;
        if (errorCode !== "ENOENT") {
          if (ledger) {
            ledger.recordEvent("system", `skipped_unreadable_file:${relPath}`, "warning", {
              reason: "file could not be read",
              error: err instanceof Error ? err.message : String(err),
            });
          }
          continue;
        }
        // File may not exist yet because the patch plan will create it.
      }

      selectedFiles.push({
        path: relPath,
        reason: "Selected for task execution",
        content,
      });
    }

    const fileSelectionResult: FileSelectionResult = {
      selectedFiles,
    };

    return {
      fileSelectionResult,
    };
  };
}

export function createPatchPlanNode(llm: LlmProvider): AgentNode {
  return async (state) => {
    const ledger = activeLedgers.get(state.context.sessionId);

    if (isReviewOnlyTask(state.query)) {
      const patchPlan: PatchPlan = {
        rationale: "Review-only dry-run: no file changes are proposed by the deterministic mock provider.",
        chunks: [],
      };

      if (ledger) {
        ledger.recordEvent("system", "review_only_patch_plan", "info", {
          chunkCount: 0,
        });
      }

      return {
        patchPlan,
        messages: [
          {
            id: crypto.randomUUID(),
            role: "assistant",
            content: `Patch Plan:\nRationale: ${patchPlan.rationale}\nChunks:\n`,
            timestamp: new Date().toISOString(),
          },
        ],
      };
    }

    const systemPrompt = `Return JSON object only. No markdown. No prose.
Schema: ${PATCH_PLAN_JSON_SCHEMA_PROMPT}
Example: {"rationale":"Add trace ledger tests.","chunks":[{"type":"create","file":"packages/core/src/__tests__/trace-ledger.test.ts","description":"Create focused trace ledger tests."}]}
Rules:
- Do not include code, diffs, content, targetContent, markdown, or extra fields.
- Use at most 5 chunks.
- If no file changes are appropriate, return {"rationale":"...","chunks":[]}.`;
    const contextPack = await resolveContextPack(state);
    const compactContext = compactContextForPrompt(contextPack);
    const selectedFilesSummary = summarizePatchSelectionForPrompt(state.fileSelectionResult?.selectedFiles ?? []);
    const userMessage = `${PATCH_CONTEXT_PROMPT_MARKER}:
${JSON.stringify({
  task: state.query,
  context: compactContext,
  scopeAnalysisResult: {
    rationale: state.scopeAnalysisResult?.rationale ?? null,
    proposedFilesToModify: state.scopeAnalysisResult?.proposedFilesToModify ?? [],
    proposedFilesToCreate: state.scopeAnalysisResult?.proposedFilesToCreate ?? [],
  },
  selectedFiles: selectedFilesSummary,
  validationSuccess: state.validationResult?.success ?? null,
  validationErrors: state.validationResult?.errors.slice(0, 3) ?? [],
})}`;

    const messages: AgentMessage[] = [
      ...state.messages,
      {
        id: crypto.randomUUID(),
        role: "system",
        content: systemPrompt,
        timestamp: new Date().toISOString(),
      },
      {
        id: crypto.randomUUID(),
        role: "user",
        content: userMessage,
        timestamp: new Date().toISOString(),
      },
    ];

    const maxTokens = state.context.patchPlanMaxTokens ?? DEFAULT_PATCH_PLAN_MAX_TOKENS;
    const responseFormat = resolveStructuredOutputFormatMode(state);

    if (ledger) {
      ledger.recordEvent(
        "llm_call",
        "patch_plan",
        "info",
        providerPayload(state, llm, "patch_plan", messages, responseFormat, maxTokens)
      );
    }

    let patchPlan: PatchPlan;
    let completion: LlmCompletionResult | undefined;
    let retryAttempt = 0;
    let retryAttempted = false;
    let retrySucceeded = false;
    try {
      const structured = await generateStructuredWithRetry(
        state,
        llm,
        "patch_plan",
        messages,
        maxTokens,
        PATCH_PLAN_JSON_SCHEMA,
        responseFormat,
        {
          task: state.query,
          selectedFiles: selectedFilesSummary.map((file) => file.file),
          contextCandidateFiles: compactContext.candidateFiles.length,
          contextIncludedFiles: compactContext.compactFileSummaries.length,
        },
        (candidate) => parsePatchPlanResponse(candidate.content, {
          provider: llm.providerName,
          model: llm.modelName,
          purpose: "patch_plan",
          finishReason: candidate.finishReason,
        })
      );
      const parsedPatchPlan = structured.parsed;
      completion = structured.completion;
      retryAttempt = structured.retryAttempt;
      retryAttempted = structured.retryAttempted;
      retrySucceeded = structured.retrySucceeded;
      const groundedPatch = applyPatchGrounding(state, parsedPatchPlan.patchPlan, contextPack);
      patchPlan = {
        ...parsedPatchPlan.patchPlan,
        chunks: groundedPatch.acceptedChunks,
        groundingNotes: [
          ...groundedPatch.groundingNotes,
        ],
        rejectedChunks: groundedPatch.rejectedChunks,
      };
      if (ledger && parsedPatchPlan.repairs.length > 0) {
        ledger.recordEvent("system", "provider_schema_repaired", "warning", {
          provider: llm.providerName,
          model: llm.modelName,
          purpose: "patch_plan",
          repairs: parsedPatchPlan.repairs,
        });
      }
      if (ledger) {
        ledger.recordEvent("tool_response", "patch_plan_response", "info", {
          provider: llm.providerName,
          model: llm.modelName,
          purpose: "patch_plan",
          parseCategory: "ok",
          schemaValidationPath: null,
          validationStatus: "valid",
          finishReason: completion.finishReason ?? null,
          contentLength: completion.content.length,
          responseShape: completion.responseShape ?? null,
          responseFormatRequested: true,
          responseFormatType: responseFormat,
          retryAttempt,
          retryAttempted,
          retrySucceeded,
          groundingNotes: groundedPatch.groundingNotes,
          rejectedChunkCount: groundedPatch.rejectedChunks.length,
          schemaRepairCount: parsedPatchPlan.repairs.length,
          tokenUsage: completion.usage ?? null,
        });
      }
    } catch (err: unknown) {
      const providerError = err instanceof ProviderJsonOutputError
        ? err
        : null;
      if (ledger) {
        ledger.recordEvent(
          "tool_response",
          "patch_plan_response",
          "error",
          providerErrorPayload(
            llm,
            "patch_plan",
            err,
            completion?.usage,
            completion?.finishReason,
            completion?.content.length,
            true,
            responseFormat,
            providerError?.retryAttempt ?? retryAttempt,
            providerError?.retryAttempted ?? retryAttempted,
            providerError?.retrySucceeded ?? retrySucceeded,
            completion?.responseShape,
          )
        );
      }
      throw err;
    }

    return {
      patchPlan,
      messages: [
        {
          id: crypto.randomUUID(),
          role: "assistant",
          content: `Patch Plan:\nRationale: ${patchPlan.rationale}\nChunks:\n${patchPlan.chunks.map((c) => `- ${c.type.toUpperCase()} ${c.file}: ${c.description}`).join("\n")}`,
          timestamp: new Date().toISOString(),
        },
      ],
    };
  };
}

export function createOptionalPatchApplyNode(): AgentNode {
  return async (state) => {
    const ledger = activeLedgers.get(state.context.sessionId);
    const dryRun = state.context.dryRun;
    const patchPlan = state.patchPlan;
    const scopeAnalysis = state.scopeAnalysisResult;
    const chunks = patchPlan?.chunks ?? [];
    const writeResult = {
      attempted: chunks.length,
      created: [] as string[],
      skipped: [] as Array<{ readonly file: string; readonly reason: string }>,
      rejected: [] as Array<{ readonly file: string; readonly reason: string }>,
    };

    if (!patchPlan || chunks.length === 0) {
      if (ledger) {
        ledger.recordEvent("system", "patch_write_summary", "info", {
          dryRun,
          chunksAttempted: 0,
          created: 0,
          skipped: 0,
          rejected: 0,
        });
      }

      if (!dryRun) {
        return {
          writeResult,
          error: "No safe create chunks available in write mode.",
        };
      }

      return {
        writeResult,
      };
    }

    if (dryRun) {
      if (ledger) {
        ledger.recordEvent("system", "dry_run_patch_apply", "info", {
          rationale: patchPlan.rationale,
          chunks,
          message: "Dry-run mode: no files modified.",
        });
      }

      return {
        writeResult,
      };
    }

    const repoRoot = state.context.workspaceDir;
    const affectedModules = scopeAnalysis?.affectedModules ?? [];

    // Safety check: validate ALL grounded paths before any writes.
    const allPaths = chunks.map((chunk) => chunk.file);
    try {
      assertWriteSafe(repoRoot, allPaths);
    } catch (err: unknown) {
      if (err instanceof SafetyViolationError) {
        if (ledger) {
          ledger.recordEvent("system", "safety_violation_abort", "error", {
            violatingPath: err.violatingPath,
            reason: err.reason,
          });
        }
        // Re-throw to abort the run.
        throw err;
      }
      throw err;
    }

    let writeFailed = false;
    let safeCreateChunks = 0;
    for (const chunk of chunks) {
      if (chunk.type !== "create") {
        writeResult.rejected.push({
          file: chunk.file,
          reason: `chunk type ${chunk.type} is not supported in write mode; only create chunks are applied`,
        });
        continue;
      }

      const normalizedPath = isRepoRelativePathLike(chunk.file);
      if (!normalizedPath) {
        writeResult.rejected.push({
          file: chunk.file,
          reason: "not a valid repo-relative path",
        });
        continue;
      }

      if (!isAllowedNewTestFile(normalizedPath, repoRoot, affectedModules)) {
        writeResult.rejected.push({
          file: chunk.file,
          reason: "only new test files under test paths are allowed in write mode",
        });
        continue;
      }
      safeCreateChunks += 1;

      const targetPath = path.join(repoRoot, normalizedPath);
      try {
        const existing = await fs.stat(targetPath);
        if (existing.isFile()) {
          writeResult.skipped.push({
            file: normalizedPath,
            reason: "target file already exists",
          });
        } else {
          writeResult.rejected.push({
            file: normalizedPath,
            reason: "target path exists and is not a regular file",
          });
          writeFailed = true;
        }
        continue;
      } catch (err: unknown) {
        const code = typeof err === "object" && err !== null && "code" in err
          ? String((err as { code?: unknown }).code)
          : "unknown";
        if (code !== "ENOENT") {
          writeResult.rejected.push({
            file: normalizedPath,
            reason: `target path is not accessible (${code})`,
          });
          writeFailed = true;
          continue;
        }
      }

      try {
        await fs.mkdir(path.dirname(targetPath), { recursive: true });
        await fs.writeFile(
          targetPath,
          buildTestFileContent(normalizedPath, chunk.description),
          "utf-8"
        );
        writeResult.created.push(normalizedPath);
      } catch (err: unknown) {
        writeResult.rejected.push({
          file: normalizedPath,
          reason: err instanceof Error ? err.message : String(err),
        });
        writeFailed = true;
      }
    }

    if (ledger) {
      ledger.recordEvent("system", "patch_write_summary", "info", {
        dryRun,
        attempted: writeResult.attempted,
        createdCount: writeResult.created.length,
        skippedCount: writeResult.skipped.length,
        rejectedCount: writeResult.rejected.length,
      });
    }

    if (writeFailed) {
      return {
        writeResult,
        error: "Write mode failed while applying patch chunks. Review rejected files in report and rerun after adjustments.",
      };
    }

    if (safeCreateChunks === 0 || writeResult.created.length === 0) {
      return {
        writeResult,
        error: "No safe create chunks available in write mode.",
      };
    }

    return {
      writeResult,
    };
  };
}

export function createValidationNode(): AgentNode {
  return async (state) => {
    const ledger = activeLedgers.get(state.context.sessionId);
    const decision = resolveValidationDecision(state);

    if (ledger) {
      ledger.recordEvent("system", "validation_decision", "info", {
        source: decision.source,
        confidence: decision.confidence,
        reason: decision.reason,
        command: decision.command,
      });
    }

    if (decision.source === "unavailable") {
      const validationResult: ValidationResult = {
        success: false,
        validationDecision: decision,
        commandsRun: [],
        errors: [decision.reason],
      };

      return {
        validationResult,
        error: decision.reason,
      };
    }

    const testCommand = decision.command;
    const startTime = Date.now();
    let stdout = "";
    let stderr = "";
    let exitCode = 0;

    if (isPlaceholderValidationCommand(testCommand)) {
      stdout = "placeholder validation skipped\n";
    } else {
      try {
        const result = await execAsync(testCommand, { cwd: state.context.workspaceDir });
        stdout = result.stdout;
        stderr = result.stderr;
      } catch (err: unknown) {
        const execErr = err as { code?: number; stdout?: string; stderr?: string };
        exitCode = execErr.code ?? 1;
        stdout = execErr.stdout ?? "";
        stderr = execErr.stderr ?? "";
      }
    }

    const durationMs = Date.now() - startTime;
    const validationResult: ValidationResult = {
      success: exitCode === 0,
      validationDecision: decision,
      commandsRun: [
        {
          command: testCommand,
          stdout,
          stderr,
          exitCode,
          durationMs,
        },
      ],
      errors: exitCode !== 0 ? [stderr || stdout || "Test command failed"] : [],
    };

    return {
      validationResult,
      messages: [
        {
          id: crypto.randomUUID(),
          role: "user",
          content: `Validation Results:\nSuccess: ${validationResult.success}\nExit Code: ${exitCode}\nStdout: ${stdout}\nStderr: ${stderr}`,
          timestamp: new Date().toISOString(),
        },
      ],
    };
};
}

export function createTraceExportNode(): AgentNode {
  return async (state) => {
    const runId = state.context.sessionId;
    const ledger = activeLedgers.get(runId);

    const runDir = state.context.outputDir;
    await fs.mkdir(runDir, { recursive: true });

    // Write patch-plan.json
    const patchPlan = state.patchPlan ?? { chunks: [], rationale: "No patch plan generated." };
    await fs.writeFile(
      path.join(runDir, "patch-plan.json"),
      JSON.stringify(patchPlan, null, 2),
      "utf-8"
    );

    // Write selected-files.json
    const selectedFiles = state.fileSelectionResult ?? { selectedFiles: [] };
    await fs.writeFile(
      path.join(runDir, "selected-files.json"),
      JSON.stringify(selectedFiles, null, 2),
      "utf-8"
    );

    // Write applied-files.json
    const writeResult = state.writeResult ?? {
      attempted: 0,
      created: [],
      skipped: [],
      rejected: [],
    };
    await fs.writeFile(
      path.join(runDir, "applied-files.json"),
      JSON.stringify(writeResult, null, 2),
      "utf-8"
    );

    if (ledger) {
      const summary = ledger.getSummary();
      await fs.writeFile(
        path.join(runDir, "trace.json"),
        JSON.stringify(summary, null, 2),
        "utf-8"
      );
    }

    return {};
  };
}

export function createReportExportNode(): AgentNode {
  return async (state) => {
    const runId = state.context.sessionId;
    const ledger = activeLedgers.get(runId);

    const writeResult = state.writeResult ?? {
      attempted: 0,
      created: [],
      skipped: [],
      rejected: [],
    };
    const filesModified = writeResult.created;
    const validationAttempted = state.validationResult !== undefined;
    const validationSuccess = state.validationResult?.success ?? false;
    const patchApplied = !state.context.dryRun && writeResult.created.length > 0;
    const patchPlanPath = `.codepawl/runs/${runId}/patch-plan.json`;
    const rejectedScopeModifications = state.scopeAnalysisResult?.rejectedProposedFilesToModify ?? [];
    const rejectedScopeCreations = state.scopeAnalysisResult?.rejectedProposedFilesToCreate ?? [];
    const rejectedPatchChunks = state.patchPlan?.rejectedChunks ?? [];
    const scopeRejections = [
      ...rejectedScopeModifications.map((entry) => `modify: ${entry.file} (${entry.reason})`),
      ...rejectedScopeCreations.map((entry) => `create: ${entry.file} (${entry.reason})`),
    ];
    const patchRejections = rejectedPatchChunks.map(
      (chunk) => `#${chunk.index + 1} ${chunk.file} (${chunk.reason})`
    );
    const validationDecision = state.validationResult?.validationDecision;

    let durationMs = 0;
    let tokenUsage = { input: 0, output: 0, total: 0 };

    if (ledger) {
      const summary = ledger.getSummary();
      durationMs = summary.totalDurationMs;
      tokenUsage = {
        input: summary.tokenUsage.input,
        output: summary.tokenUsage.output,
        total: summary.tokenUsage.total,
      };
    }

    const readiness = state.readinessGateResult;

    const reportResult: ReportResult = {
      summary: `Agent run finished with status: ${validationSuccess ? "success" : "failed"}.`,
      filesModified,
      filesCreated: writeResult.created,
      filesSkipped: writeResult.skipped,
      filesRejected: writeResult.rejected,
      patchApplied,
      validationSuccess,
      durationMs,
      tokenUsage,
      validationDecision,
      readiness,
    };

    const runDir = state.context.outputDir;
    await fs.mkdir(runDir, { recursive: true });

    // Risk notes
    const riskNotes: string[] = [];
    if (!state.context.dryRun && filesModified.length > 0) {
      riskNotes.push("Write mode was active — files may have been modified.");
    }
    if (!state.context.dryRun && writeResult.skipped.length > 0) {
      riskNotes.push(`Write mode skipped ${writeResult.skipped.length} chunk(s) without creating files.`);
    }
    if (!state.context.dryRun && writeResult.rejected.length > 0) {
      riskNotes.push(`Write mode rejected ${writeResult.rejected.length} chunk(s) due to write policy.`);
    }
    if (state.error) {
      riskNotes.push(`Agent encountered an error: ${state.error}`);
    }
    if (scopeRejections.length > 0) {
      riskNotes.push(`Scope analysis filtered ${scopeRejections.length} ungrounded path proposal(s).`);
    }
    if (state.scopeAnalysisResult?.groundingFallbackUsed) {
      const fallbackFiles = state.scopeAnalysisResult.groundingFallbackFiles ?? [];
      riskNotes.push(
        `Provider proposed ungrounded scope paths; fallback context file(s) were used: ${fallbackFiles.join(", ") || "none available"}`
      );
    }
    if (readiness?.status === "unsupported") {
      riskNotes.push("Readiness gate rejected this task as unsupported for this workflow.");
    }
    if (readiness?.status === "unsafe") {
      riskNotes.push("Readiness gate blocked execution for unsafe or destructive intent.");
    }
    if (readiness?.status === "needs_clarification") {
      riskNotes.push("Readiness gate blocked execution because the task is under-specified.");
    }
    if (readiness && readiness.status !== "ready") {
      riskNotes.push("Readiness gate blocked the run before provider planning; no provider calls were made.");
    }
    if (patchRejections.length > 0) {
      riskNotes.push(`Patch plan filtered ${patchRejections.length} ungrounded chunk(s).`);
    }
    const writeModeNoSafeCreateFailure =
      !state.context.dryRun && state.error?.includes("No safe create chunks available in write mode.") === true;

    if (writeModeNoSafeCreateFailure) {
      riskNotes.push("Write mode failed before validation because no safe create chunks were available.");
    } else if (validationDecision?.source === "unavailable") {
      riskNotes.push(`Validation was blocked: ${validationDecision.reason}`);
    } else if (!validationAttempted && state.error) {
      riskNotes.push("Validation was not run.");
    } else if (!validationSuccess) {
      riskNotes.push("Validation failed — review errors before merging.");
    }

    // GitHub-ready Markdown report
    const validationSection = validationAttempted
      ? [
          `**Validation Decision:** ${validationDecision?.source ?? "unavailable"} (confidence ${validationDecision?.confidence ?? 0})`,
          validationDecision?.reason ? `- Reason: ${validationDecision.reason}` : "",
          validationDecision?.command ? `- Command: \`${validationDecision.command}\`` : "",
          ...(state.validationResult?.commandsRun.length
            ? state.validationResult.commandsRun.map((cmd) => {
              const label = isPlaceholderValidationCommand(cmd.command)
                ? "Placeholder validation"
                : "Validation command";
              return `**${label}:** \`${cmd.command}\`\n` +
                `- Exit Code: ${cmd.exitCode}\n` +
                `- Duration: ${cmd.durationMs}ms\n` +
                (cmd.stdout ? `- Stdout:\n\`\`\`\n${cmd.stdout.slice(0, 2000)}\n\`\`\`\n` : "") +
                (cmd.stderr ? `- Stderr:\n\`\`\`\n${cmd.stderr.slice(0, 2000)}\n\`\`\`\n` : "");
            })
            : ["No validation command was executed."])
        ].join("\n")
      : "_Not run._";

    const traceTimeline = ledger
      ? ledger
          .getSummary()
          .events.slice(-20)
          .map((e) => `| ${e.timestamp} | ${e.type} | ${e.name} | ${e.severity} |`)
          .join("\n")
      : "_No trace events._";

    const contextSection = state.contextPack
      ? `## 🧩 Context Pack

**Included file count:** ${state.contextPack.metrics.includedFiles}
**Omitted file count:** ${state.contextPack.metrics.omittedFiles}
**Context budget:** files <= ${state.contextPack.budget.maxFiles}, bytes <= ${state.contextPack.budget.maxBytes}, chars <= ${state.contextPack.budget.maxChars}
**Context compacted:** ${state.contextPack.metrics.compactionReason === "none" ? "No (within budget)" : "Yes"}
**Candidate file count:** ${state.contextPack.metrics.candidateFiles}

Safety exclusions:
- ${state.contextPack.safetyExclusions.length > 0 ? state.contextPack.safetyExclusions.join("\\n- ") : "None"}

_Full prompts are not stored by default in trace or report; only compact metrics and bounded metadata are recorded._`
      : "## 🧩 Context Pack\n\nContext pack was not generated for this run.";

    const readinessSection = readiness
      ? `## 🚦 Readiness Gate

**Status:** ${readiness.status}

${readiness.reasons.length > 0 ? `**Reasons:**\n${readiness.reasons.map((reason) => `- ${reason}`).join("\n")}` : "_No specific reasons._"}
${readiness.blockers.length > 0 ? `**Blockers:**\n${readiness.blockers.map((blocker) => `- ${blocker}`).join("\n")}` : ""}
${readiness.warnings.length > 0 ? `**Warnings:**\n${readiness.warnings.map((warning) => `- ${warning}`).join("\n")}` : ""}`
      : "## 🚦 Readiness Gate\n\n_Ready check did not run for this execution._";

    const reportMd = `# 🐾 Openpawl Agent Run Report

> **Run ID:** \`${runId}\`
> **Mode:** ${state.context.dryRun ? "🔍 Dry-run (no files modified)" : "✏️ Write mode"}
> **Status:** ${validationSuccess ? "✅ SUCCESS" : "❌ FAILED"}
> **Duration:** ${durationMs}ms
> **Tokens Used:** ${tokenUsage.total} (in: ${tokenUsage.input}, out: ${tokenUsage.output})

---

## 📋 Task Summary

**Task:** ${state.query}

${state.scopeAnalysisResult ? `**Scope Rationale:** ${state.scopeAnalysisResult.rationale}` : ""}

${readinessSection}

---

${state.error ? `## Error\n\n\`\`\`\n${state.error}\n\`\`\`\n\n---\n\n` : ""}

${contextSection}

---

## 📁 Scope Summary

${
  state.scopeAnalysisResult
    ? `**Affected Modules:**
${state.scopeAnalysisResult.affectedModules.map((m) => `- ${m}`).join("\n")}

**Proposed Modifications:**
${state.scopeAnalysisResult.proposedFilesToModify.map((f) => `- \`${f}\``).join("\n") || "_None_"}

**Proposed Creations:**
${state.scopeAnalysisResult.proposedFilesToCreate.map((f) => `- \`${f}\``).join("\n") || "_None_"}`
    : "_Scope analysis not available._"
}

${
  scopeRejections.length > 0
    ? `### Rejected/un-grounded scope proposals

${scopeRejections.map((entry) => `- ${entry}`).join("\n")}`
    : ""
}

---

## 📂 Selected Files

${
  state.fileSelectionResult && state.fileSelectionResult.selectedFiles.length > 0
    ? state.fileSelectionResult.selectedFiles
        .map((f) => `- \`${f.path}\` — ${f.reason}`)
        .join("\n")
    : "_No files selected._"
}

---

## 🔧 Patch Plan

${
  state.patchPlan
    ? `**Rationale:** ${state.patchPlan.rationale}

Patch plans are metadata-only in the current MVP. They describe intended file-level work and do not include code diffs or replacement content.

| # | Type | File | Description |
|---|------|------|-------------|
${state.patchPlan.chunks.map((c, i) => `| ${i + 1} | \`${c.type}\` | \`${c.file}\` | ${c.description} |`).join("\n")}

**Applied:** ${patchApplied ? "✅ Yes" : "⏭️ No (dry-run or no chunks)"}`
    : "_No patch plan generated._"
}

### File write summary

${
  state.context.dryRun
    ? "No files written in dry-run mode."
    : `**Attempted chunks:** ${writeResult.attempted}
**Created:** ${writeResult.created.length}
**Skipped:** ${writeResult.skipped.length}
**Rejected:** ${writeResult.rejected.length}

Created files:
${writeResult.created.map((file) => `- \`${file}\``).join("\n") || "_None_"}

Skipped files:
${writeResult.skipped.map((item) => `- \`${item.file}\` (${item.reason})`).join("\n") || "_None_"}

Rejected files:
${writeResult.rejected.map((item) => `- \`${item.file}\` (${item.reason})`).join("\n") || "_None_"}`
}

${
  patchRejections.length > 0
    ? `### Rejected/un-grounded patch chunks

${patchRejections.map((entry) => `- ${entry}`).join("\n")}`
    : ""
}

---

## ✅ Validation Result

**Overall:** ${validationAttempted ? (validationSuccess ? "✅ PASSED" : "❌ FAILED") : "Not run"}

${validationSection}

---

## 📊 Trace Timeline (last 20 events)

| Timestamp | Type | Name | Severity |
|-----------|------|------|----------|
${traceTimeline}

---

## ⚠️ Risk Notes

${riskNotes.length > 0 ? riskNotes.map((n) => `- ${n}`).join("\n") : "_No risk notes._"}

---

## 🚀 Next Suggested Human Action

${
  state.error
        ? `1. Review the error: \`${state.error}\`\n2. Fix the underlying issue and re-run.`
        : validationSuccess
          ? patchApplied
            ? "1. Review the applied patch in the run artifacts.\n2. Run your full test suite.\n3. Open a pull request if satisfied."
            : `1. This was a dry-run or no files were created. Review the patch plan in \`${patchPlanPath}\`.\n2. Re-run with \`--write\` after adjusting write-safe targets.`
          : "1. Review validation errors above.\n2. Inspect the patch plan and adjust if needed.\n3. Re-run after fixing the issues."
}

---
_Generated by [Openpawl](https://github.com/codepawl/codepawl) — server-side coding-agent workflow_
`;

    await fs.writeFile(path.join(runDir, "report.md"), reportMd, "utf-8");
    await fs.writeFile(
      path.join(runDir, "run.json"),
      JSON.stringify(reportResult, null, 2),
      "utf-8"
    );

    return {
      reportResult,
      isComplete: true,
      nextNode: null,
    };
  };
}
